### PR TITLE
aws - apigw cross-account, handle policy mangling and use correct default

### PR DESCRIPTION
**Pull request by baolsen**
Re-open of https://github.com/cloud-custodian/cloud-custodian/pull/5885

Closes: #6258
Closes: #5878

### CODE REVIEW

**Comment by kapilt** [comment]
thanks, I think the problem with the original pr (ie why it was in draft), was that it was missing a unit test, which still needs to be added.

**Comment by kapilt** [comment]
I've gone ahead and added a unit test to the original pr, thanks for raising awareness.

**Review by kapilt — APPROVED** [review]
lgtm

**Comment by baolsen** [comment]
@kapilt Thanks for the assist.
I have another unit test I'll try to add

**Comment by baolsen** [comment]
@kapilt ready to merge :)

**Pull request merged**
