### PR TITLE
wip - Permissions cli

### PR DESCRIPTION
**Pull request by thisisshi**
adding support for getting permissions in a json file (permissions.json) for now, should be user configurable in the future

will clean up the cli options

### CODE REVIEW

**Comment by kapilt** [comment]
This seems very aws specific and will break on other providers, unless it’s generalized it probably in tools/ops

**Comment by kapilt** [comment]
Also not sure it’s particularly usable output in this form.

**Comment by kapilt** [comment]
Also wrt to in future ref, cli is public interface contract so it’s better to have a proposal/issue for discussing design, as forward compatibility concerns arise if it changes

**Comment by thisisshi** [comment]
closing for now until there's a better proposal on this interface

**Pull request closed without merging**
