### PR TITLE
update offhours tag restrictions

### PR DESCRIPTION
**Pull request by connorSanderson**
Update escape characters to allow the hyphen character to be escaped for resources which do not allow it as a tag value. For example, ecs services' tags.

### CODE REVIEW

**Comment by kapilt** [comment]
if this is ecs specific it feels like should handle it specific to that type, rather than force the default for resources where it is compatible

**Comment by kentnsw** [comment]
@connorSanderson @kapilt

Just want to add my understanding here. The "escape" feature in c7n is "decode" only, no "encode". It is to "decode" those escaped characters in tag value back to normal, eg, from `u28` to `(`.

If the `(` is supported by the tag value, user does not have to escape it, eg, in EC2 tag value, we can use normal string like `off=(M-F,19);on=(M-F,7)`. But when comes to RDS, user has to "encode" `(` to `u28` to adapt to the restriction.

So IMHO, this PR looks good.

**Review by kentnsw — APPROVED** [review]

**Comment by kapilt** [comment]
thanks @kentnsw for the explanation

**Review by kapilt — COMMENTED** [review]
lgtm

**Pull request merged**
