### PR TITLE
update lambda policy for s3 output_dir to support {{account}} and {{account_id}}

### PR DESCRIPTION
**Pull request by yuriydee**
Currently 
```
mode:
  execution-options:
    output_dir: s3://my-s3-bucket/
```
does not support {{ account }} or {{ account_id }} as a key-prefix. 

Updated it to process either option if present, otherwise return defined bucket & prefix. 

This should work now:
```
mode:
  execution-options:
    output_dir: s3://my-s3-bucket/{{account}}
```
or
```
mode:
  execution-options:
    output_dir: s3://my-s3-bucket/path/{account_id}
```

Currently this wouldnt support `output_dir: s3://my-s3-bucket/{account_id}/another-path`

### CODE REVIEW

**Comment by kapilt** [comment]
{account_id} was already supported,  not supporting {account} was a purposeful choice as aliases are mutable.

**Comment by yuriydee** [comment]
For the alias, why would them being mutable cause issues? In that case it would just go to a different bucket prefix anyways right?

**Comment by kapilt** [comment]
best practice is treating output folders as audit records, if your mutating the location for an accounts records, its much harder to find and trace through on history.

**Comment by yuriydee** [comment]
Hm fair point. The alias shouldnt be changed on a whim either imo but i understand anything can happen. I agree with keeping AWS patterns. You can deny the PR.

**Comment by kapilt** [comment]
@yuriydee thanks for sending in a pull request btw.

**Pull request closed without merging**
