### PR TITLE
Add filter for S3 public access block configuration

### PR DESCRIPTION
**Pull request by mrwacky42**
Attempt at adding filters for S3 bucket public access block configuration (see #3146).

I am looking for advice on how to teach this to do something useful.

### CODE REVIEW

**Comment by kapilt** [comment]
s3 historically has had this table of augments to assemble various bits of information for a bucket to enable easy filtering with the builtin generic value filter. For such attributes no dedicated filter is needed. However for newer features we defer to having the filter perform the api call to collect the needed information, which makes the retrieval of such information explicit and lessons the api calls custodian needs to do if this information is not germane to a policy.

**Comment by kapilt** [comment]
additionally for contributions pull requests the custodian project has a historical cla that we request contributors to sign.  If you don't mind could you sign the CLA at the bottom of the README? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by mrwacky42** [comment]
@kapilt  - Can you show an example of a more modern filter? The code I have now does inject the policies, but I still do not understand how the filter is supposed to work to validate against the schema.

**Comment by kapilt** [comment]
preferrable is doing the api call in the filter to fetch the status and annotate the resource with it, and then invoke the value filter, many of the filters for other resources are setup that way.

**Comment by kapilt** [comment]
@mrwacky42 ping re cla?

**Comment by mrwacky42** [comment]
Hi @kapilt - I ended up not using Cloud Custodian. Feel free to close this PR, I don't have time to improve it.

**Comment by JohnHillegass** [comment]
@kapilt, I believe that this can be closed because of the addition of #5451. I'd update myself but it seems these permissions are locked down a bit, which makes sense.

**Comment by JohnHillegass** [comment]
Closed with addition of #5451

**Pull request closed without merging**
