### PR TITLE
move to per-service checks to address #3794 and others

### PR DESCRIPTION
**Pull request by tjstansell**
This is an attempt to get the `service-limits` filter working again to help with #3794 and others. Until #4251 is ready, it seemed we should at least query the correct service checks for the existing `service-limits` filter.  This tried to keep the same filter attributes and do something intelligent with them.  Unfortunately, we don't have access to the actual `service` name until after we query each check, but we can fairly accurately infer the service name from the prefix of the name of the check.

Each `service_limits` check seems to map to a single check, with results for each region.  The names of each service check also can slightly diverge from the name returned in the results.  However, the console UI uses the check name, so that's what I'm matching against to filter which checks to query (since we have to make an api call for each check).

I don't have any of the tests updated yet, but wanted to put this up to start the initial review.

### CODE REVIEW

**Comment by tjstansell** [comment]
Hm... this current method of using substring matches doesn't really give us the same ability to target something like `service: VPC limits: VPCs` anymore since the name of the check is just `VPC` for that.  For instance, these are all of the VPC checks and the results service and check names:
```
Check ID        Check Name              Result [Service, Name]
jL7PP0l7J9	VPC                     ["VPC","VPCs"]
kM7QQ0l7J9	VPC Internet Gateways	["VPC","Internet gateways"]
lN7RR0l7J9	VPC Elastic IP Address	["VPC","VPC Elastic IP addresses (EIPs)"]
```
Maybe we should filter which checks to query based on the service name, like we're doing, but then filter all of the results with a full match against the result name with anything listed in the `limits` attribute.

@kapilt thoughts on this?

**Comment by tjstansell** [comment]
Now I'm thinking we should keep the `limits` attribute the same, comparing against any of the results we get back.  But perhaps we should add a new field called `name-filter` or `names` or something that could be used to filter which checks to actually query.  It would be great if it could be a ValueFilter or similar could support `and`, `or`, `contains`, `eq`, etc to allow flexibility in how to filter things... but at the same time, it would simplify things a lot of it worked basically the same as `limits` and just did a comparison against the full name (maybe making all of these case-insensitive since they seem a bit inconsistent on their use of case).

**Comment by kapilt** [comment]
wow, thanks for digging into this, I had hoped we be able to move to service quotas for read/write on these, but we ran into some api oddities there, moving to the individual trusted advisor checks is also quite nice.

**Comment by kapilt** [comment]
quick review, this looks great, its a big diff but thats mostly related to the test recording data.

**Comment by kapilt** [comment]
still working through this, i think we can cut down the recordings quite a bit if we can mock/patch get_available_checks to just walk through the handful needed to exercise functionality here.

**Comment by kapilt** [comment]
ok, i think i've got most of the extra data recording issues cleaned up, albeit via tedious manual labor.  code wise this pr looks pretty solid. i added a few more annotations of check id / name onto the check results.

**Pull request merged**
