### PR TITLE
aws - cloudsearch Added enable-https action

### PR DESCRIPTION
**Pull request by Kiranmoka**

### CODE REVIEW

**Review by thisisshi — COMMENTED** [review]
thanks for the pr, can we also include a way to set the TLSSecurityPolicy in the action as well? we can default to `Policy-Min-TLS-1-0-2019-07` if no value is provided

**Comment by Kiranmoka** [comment]
> thanks for the pr, can we also include a way to set the TLSSecurityPolicy in the action as well? we can default to `Policy-Min-TLS-1-0-2019-07` if no value is provided

Thanks for your reply, I've added TLSSecurityPolicy to the action.

**Comment by kapilt** [comment]
we might need a filter (domain-options) to accompany this, we generally want policies that only fire actions if a set of preconditions is true (https not enabled for example).

**Review by kapilt — APPROVED** [review]
lgtm, thanks, i made some minor tweaks to the syntax of the filter, so that it can be used against any of the domain settings.

**Pull request merged**
