### PR TITLE
mailer - fix module not found error for azure mailer

### PR DESCRIPTION
**Pull request by thisisshi**
closes https://github.com/cloud-custodian/cloud-custodian/issues/8179

### CODE REVIEW

**Review by ajkerrigan — COMMENTED** [review]
Thanks for jumping on this, good catch. I _think_ we'll need at least one more late import, opened a PR to your branch [here](https://github.com/thisisshi/cloud-custodian/pull/26) for that.

Might be missing something though :thinking:

**Comment by ajkerrigan** [comment]
Dang lemme get a test together for that late SNS import. Coverage is angry

**Review by ajkerrigan — APPROVED** [review]
Approving, though I've mucked with this enough that I won't merge it myself :)

**Review by kapilt — APPROVED** [review]
lgtm

**Pull request merged**
