### PR TITLE
aws - enable offhours for rds cluster

### PR DESCRIPTION
**Pull request by oba11**
This is a followup to https://github.com/cloud-custodian/cloud-custodian/pull/3556 to automate stopping/starting of rds cluster

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks for the pull request!  If you don't mind could you sign the CLA at the bottom of the README? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by oba11** [comment]
@kapilt Thanks for taking a look at the PR, I did sign the CLA before opening the PR. Please can you try  to check again to avoid having duplicate entry in the form.
If it's not there, I will be more than happy to sign it. Thanks again

**Comment by kapilt** [comment]
yup.. your all good, thanks

**Comment by oba11** [comment]
Thanks to you @kapilt 👍

**Pull request merged**
