### PR TITLE
c7n-left - graph get refs handle ref blocks that aren't resolved

### PR DESCRIPTION
**Pull request by kapilt**
graph get refs on a block could potentially reference a block without basic tfmeta information
this seems to be the case with certain module references w/ for each that aren't fully resolved.

### CODE REVIEW

**Review by ajkerrigan — APPROVED** [review]
Good call, lgtm :+1:

**Comment by kapilt** [comment]
so it looks like the ref map gets populated with a module ref that's not fully resolved, but when it is resolved its no longer in the block because the ref is back to individual block elements.

so this block
```python
{'__tfmeta': {'filename': '.terraform/modules/eventbridge/iam.tf',
              'label': 'aws_iam_role',
              'line_end': 42,
              'line_start': 31,
              'path': 'module.eventbridge.aws_iam_role.eventbridge[0]',
              'src_dir': PosixPath('terraform'),
              'type': 'resource'},
 'assume_role_policy': {'__attribute__': 'data.aws_iam_policy_document.assume_role[0].json',
                        '__name__': 'assume_role[0]',
                        '__ref__': 'f34a9af6-62a3-4417-bbfc-ceba1d173814',
                        '__type__': 'aws_iam_policy_document'},
 'count': 1,
 'description': None,
 'force_detach_policies': True,
 'id': '574851fc-1e0d-44a5-b860-b92947027b13',
 'name': 'default',
 'path': None,
 'permissions_boundary': None,
```

ends up with these forward refs in the ref_map

```
(Pdb) pp refs
['807376ee-c416-4fda-a379-61a4253e0c30',
 'f34a9af6-62a3-4417-bbfc-ceba1d173814',
 'a1ff0b98-8c7f-4ea0-b234-86a82cff8998']
```

but post resolution, only one is a valid ref.. at least one of the others was a variable reference that got populated. the invalid ref looks like its from the module usage block

```python
{'arn': '807376ee-c416-4fda-a379-61a4253e0c30',
 'description': 'Used to watch for account creations to deploy default '
                'configuration via the account-coniguration step function',
 'event_bus_name': 'default',
 'event_pattern': '{"detail":{"eventName":["CreateAccount"],"eventSource":["organizations.amazonaws.com"]},"detail-type":["AWS '
                  'API Call via CloudTrail"],"source":["aws.organizations"]}',
 'for_each': {'create-account-watcher': {'Name': 'create-account-watcher-rule',
                                         'description': 'Used to watch for '
                                                        'account creations to '
                                                        'deploy default '
                                                        'configuration via the '
                                                        'account-coniguration '
                                                        'step function',
                                         'event_pattern': '{"detail":{"eventName":["CreateAccount"],"eventSource":["organizations.amazonaws.com"]},"detail-type":["AWS '
                                                          'API Call via '
                                                          'CloudTrail"],"source":["aws.organizations"]}',
                                         'name': 'create-account-watcher'}},
 'force_destroy': None,
 'id': '807376ee-c416-4fda-a379-61a4253e0c30',
 'name': 'create-account-watcher-rule',
 'name_prefix': None,
 'role_arn': None,
 'schedule_expression': None,
 'state': None,
 'tags': {'Name': 'create-account-watcher-rule'}}
```

its not clear me to why this wouldn't have __tfmeta set though, which could use some further investigation.

**Comment by ajkerrigan** [comment]
Does this overlap with #9709 and/or https://github.com/cloud-custodian/tfparse/issues/99 then? And what we're seeing with the missing `__tfmeta` key is just a symptom of some other linkage getting dropped?

**Comment by kapilt** [comment]
seems distinct from that, ref building is more intrinsic, this does have a resolvable ref, but the other side of it missing the tfmeta is odd and not really related to multi ref. it seems more related to module interpolation.

**Pull request merged**
