### PR TITLE
Modify Security Groups by GroupName

### PR DESCRIPTION
**Pull request by eschultz17**
Supercedes: #2790

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks Eric, quick question is this based on #2790?

**Comment by eschultz17** [comment]
Found an issue when testing... still making updates. Please hold off on review

**Comment by kapilt** [comment]
just update the title when its good for review, thanks

**Comment by kapilt** [comment]
thanks for the pr, there's a couple of things that give me a little pause. the new ducktyping introspection on a resource vpc id, the existing duck typing introspection for sg on a resource. the multiple api calls to resolve a group of names per add/remove/isolation-group, and the carry forward of ids and names vars, and the use of name vars to actually convey sg dicts. i'd like to explore a bit more.

**Comment by kapilt** [comment]
found a few other issues while deep diving on this, going to end up refactoring this a bit.

**Comment by kapilt** [comment]
closing in favor of refactor in #3244

**Pull request closed without merging**
