### PR TITLE
Allow to pass role to subscription-filter #7609

### PR DESCRIPTION
**Pull request by dschro-1993**
PR extends the c7n-logexporter tool and allows to define an additional role-arn (as optional parameter) to create/enable ORG-based access policies on destinations.

On AWS this is documented here: [Docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CreateSubscriptionFilter-IAMrole.html)

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks for the pull request!  it looks like the easycla is failing because it can't see an associated author on the commit 
781da76 .. you can use git commit --amend --author "name <github_email>"  to correct.

**Comment by dschro-1993** [comment]
Did a `git commit --amend --reset-author --no-edit`
`git log` shows:
```
commit 80c6bd11d7143baebf984d0be25c0fac2c7b1341
Author: Schroettinger, Dominik <dominik.schroettinger@devoteam.com>
Date:   Mon Aug 8 17:51:52 2022 +0200

    allow to pass role to subscription-filter #7609
```

**Comment by kapilt** [comment]
thanks for fixing the commit signature, could you also sign the cncf/linux foundation cla, direct link per bot pr comment. https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/14202841/52837350/7617/#/?version=2

**Comment by dschro-1993** [comment]
Closed due to missing approval for CLA.

**Comment by Thanos222** [comment]
Here is the new PR:
https://github.com/cloud-custodian/cloud-custodian/pull/7657

**Pull request closed without merging**
