### PR TITLE
#6132 AccountId is not part of rule schema in same account

### PR DESCRIPTION
**Pull request by amitsehgal**
AccuntId Key isn;t avaiable for s3 buckets replicated in same account and this like ends up in error as notes in #6132

### CODE REVIEW

**Comment by kapilt** [comment]
the goal/point of the change should be to *include* it if it exists. this pr currently just blindly omits it, but cross-account replication uses cases do want for verification of account id.

**Comment by kapilt** [comment]
Thanks for the pull request!  If you don't mind could you sign the CLA per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by amitsehgal** [comment]
didn't realize cross account does have it in schema. Added as advised.

**Comment by amitsehgal** [comment]
Please review when you get a chance. Thanks. The usecase of cross-region s3 replication seems to be pretty common.

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Pull request merged**
