### PR TITLE
c7n-mailer-replay - support mimicking sqs

### PR DESCRIPTION
**Pull request by nitrocode**
Fixes https://github.com/cloud-custodian/cloud-custodian/issues/5238

### CODE REVIEW

**Comment by kapilt** [comment]
so this is basically using a dump extract of message payload in sqs and putting on the local fs?

I was thinking we should just support a file transport in notify to avoid the manual steps on pulling the message out of the queue.

**Comment by nitrocode** [comment]
I believe you mentioned that on https://github.com/cloud-custodian/cloud-custodian/issues/5238#issuecomment-575619849

I was hoping to find a workflow without having to modify my policy. The change in this PR would allow me to do the following.

1. Create/Modify policy `abc.yml`
2. `custodian run -s out --cache-period 0 --dry-run policies/abc.yml` to get the outputted data
3. `custodian report -s out policies/abc.yml` and go back to step 1 to iterate
4. Create/Modify template `abc-slack.j2`
5. Run `c7n-mailer-replay` on the outputted data without modifying the policy and go back to step 4 to iterate
6. Commit, push, PR
7. Run policy without `--dry-run`

If we created a local transport, it sounds like I'd have to modify the policy each time locally to add that transport, then remove it when I'm finished iterating.

**Comment by nitrocode** [comment]
@kapilt what do you think ? can we continue with this PR or could you describe how your local solution would allow a better workflow ?

**Review by kapilt — APPROVED** [review]
lgtm

**Pull request merged**
