### PR TITLE
Azure - Memoize Metrics Filter

### PR DESCRIPTION
**Pull request by axis7818**
#4512 

Maintain a collection of metrics that were retrieved in filters, They will appear under the `c7n:metrics` key on the resource and the objects contain the measurement, and full data payload from azure.

This is also used as a cache in the case of making multiple metrics queries with identical parameters (metric, aggregation, timeframe, interval, and filter)

```js
{
  // other resource fields
  "c7n:metrics": {
      "Percentage CPU, average, 2.0, P1D, None": {
        "measurement": [
          0.3783854166666667
        ],
        "data": {
          "cost": 0.0,
          "timespan": "2019-08-07T16:44:33Z/2019-08-07T18:44:33Z",
          "interval": "P1D",
          "namespace": "Microsoft.Compute/virtualMachines",
          "resourceregion": "eastus",
          "value": [
            {
              "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxxxxxxxxx/providers/Microsoft.Insights/metrics/Percentage CPU",
              "type": "Microsoft.Insights/metrics",
              "name": {
                "value": "Percentage CPU",
                "localized_value": "Percentage CPU"
              },
              "unit": "Percent",
              "timeseries": [
                {
                  "metadatavalues": [],
                  "data": [
                    {
                      "time_stamp": "2019-08-07T16:44:00.000Z",
                      "average": 0.3783854166666667
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
}
```

### CODE REVIEW

**Comment by axis7818** [comment]
It would be possible to leverage this as a cache when writing multiple MetricFilters in the same policy, but I am not sure how often that would be useful since each metric query is likely to use different parameters.

**Comment by stefangordon** [comment]
Hmm, so maybe cache would be useful?  If I was trying to do a threshold like `10 < x < 20` I'd have two filters with same query and a cache would help?

**Comment by axis7818** [comment]
yeah, true. I guess it would be easy enough to throw in here

**Comment by kapilt** [comment]
fwiw, the aws metrics filter does do store previously fetched metrics as an annotation, but its multi layered to account for various metrics queries, its used for repeated metrics queries against the same dimension / timespan, else its passed through to notify for reporting. note we try to minimize the size set (only one value in a series is used in comparisons, user needs to specify proper aggregate/time span) here to avoid problems with notify size limits associated to most transports.

**Comment by axis7818** [comment]
I am not too familiar with how notifications work in CC or what the acceptable payload sizes are, but it looks to me like we always pass an aggregation operation to azure, either `total` or `average`

**Pull request merged**
