### PR TITLE
releng - rev version, sphinx fixes, and rebase dependencies

### PR DESCRIPTION
**Pull request by kapilt**
- releng - upgrade dependencies, update sphinx content per warnings
- increment version
- disable aws cc provider in sphinx
- address all sphinx warnings
- fix sphinx doc cache staleness in actions
- default back to turn all warnings into errors with sphinx.
- ci now lints GitHub workflows/actions

### CODE REVIEW

**Comment by kapilt** [comment]
importlib-metadata was flapping due to argcomplete, issue filed upstream (https://github.com/kislyuk/argcomplete/issues/404) and new release (2.0.5) was made since this pr and should be included here.

**Comment by kapilt** [comment]
rebasing at least on poetry 1.4 is blocked on #8348 merging.

**Comment by kapilt** [comment]
the issues with poetry 1.4 here seem quite odd, thats already on trunk, but with the dependency rebase here we get a set  of errors on any thing with a path dependency due to poetry's installer getting confused about what's a package.

**Comment by kapilt** [comment]
given the odd poetry issues, I'm going to split the sphinx changes and poetry changes into separate prs.

**Comment by kapilt** [comment]
fixed poetry issue in [c169c25](https://github.com/cloud-custodian/cloud-custodian/pull/8341/commits/c169c253629be2fe2cd64ea4dcc02d771749fbc8)

**Review by ajkerrigan — COMMENTED** [review]
I was testing this locally and initially ran into an error installing buitl/frozen wheels in a fresh venv:

```console
ERROR: Cannot install c7n-mailer==0.6.23 and c7n==0.9.24 because these package versions have conflicting dependencies.

The conflict is caused by:
    c7n 0.9.24 depends on importlib-metadata==5.2.0
    c7n-mailer 0.6.23 depends on importlib-metadata==6.0.0
```

Then pulled in a couple more commits (running from 641717efca22e4892ae703428883b6ab89ebea45) and hit an issue during the `c7n_sphinxext` install:

```console
Because no versions of myst-parser match >0.18,<0.18.1 || >0.18.1,<0.19                                                       k  s                                
 and myst-parser (0.18.0) depends on sphinx (>=4,<6), myst-parser (>=0.18,<0.18.1 || >0.18.1,<0.19) requires sphinx (>=4,<6).
And because myst-parser (0.18.1) depends on sphinx (>=4,<6), myst-parser (>=0.18,<0.19) requires sphinx (>=4,<6).
So, because c7n-sphinxext depends on both Sphinx (~6.0) and myst-parser (^0.18), version solving failed.     
```

Tweaked the myst-parser dependency:

```diff
- myst-parser = "^0.18"
+ myst-parser = ">0.18"
```

And started getting:

```console
The current project's Python requirement (>=3.7,<4.0) is not compatible with some of the required packages Python requirement:
  - sphinx requires Python >=3.8, so it will not be satisfied for Python >=3.7,<3.8            
  - sphinx requires Python >=3.8, so it will not be satisfied for Python >=3.7,<3.8
                                                                                                                              k  s                                
Because no versions of sphinx match >6.0,<6.0.1 || >6.0.1,<6.1                                                                                                    
 and sphinx (6.0.0) requires Python >=3.8, sphinx is forbidden.
So, because sphinx (6.0.1) requires Python >=3.8                                                                                                                  
 and c7n-sphinxext depends on Sphinx (~6.0), version solving failed.
```

Will keep poking a bit later because at least _some_ of this is probably specific to my environment (Ubuntu 20.04, Poetry 1.4.0, with a Python 3.11 test virtual environment)

**Comment by kapilt** [comment]
yeah sorry I accidentally had a commit that was trying to upgrade sphinx let me yank that part. I'll have a follow up later with sphinx 6.1

**Comment by kapilt** [comment]
@ajkerrigan both of those should fixed now, I don't think it was a local issue fwiw, the action lint commit had some unfinished work.

**Comment by ajkerrigan** [comment]
> @ajkerrigan both of those should fixed now, I don't think it was a local issue fwiw, the action lint commit had some unfinished work.

Yep, looking smooth now thanks :+1:

**Review by ajkerrigan — APPROVED** [review]
lgtm :sunglasses:

**Pull request merged**
