### PR TITLE
aws  - update glue connection to handle cases where theres no VPC on the resource

### LINKED ISSUE #9162: aws - glue connection has NoneType error when no VPC
### Describe the bug

When there is no VPC on the Glue connection resource, we get a `TypeError: 'NoneType' object is not iterable` error

### What did you expect to happen?

Succeed in this case.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.32
Python:      3.9.6 (default, Aug 11 2023, 19:44:49) 
             [Clang 15.0.0 (clang-1500.0.40.1)]
```

### Policy

_No response_

### Relevant log/traceback output

```shell
ERROR    custodian.output:output.py:336 Error while executing policy
Traceback (most recent call last):
  File "/Users/timmygrable/Projects/cloud-custodian/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/timmygrable/Projects/cloud-custodian/c7n/query.py", line 549, in resources
    resources = self.filter_resources(resources)
  File "/Users/timmygrable/Projects/cloud-custodian/c7n/manager.py", line 112, in filter_resources
    resources = f.process(resources, event)
  File "/Users/timmygrable/Projects/cloud-custodian/c7n/filters/vpc.py", line 98, in process
    related = self.get_related(resources)
  File "/Users/timmygrable/Projects/cloud-custodian/c7n/filters/related.py", line 49, in get_related
    return {r[model.id]: r for r in related
TypeError: 'NoneType' object is not iterable
```

### Extra information or context

_No response_

### PR DESCRIPTION
**Pull request by timmygrable**
Closes #9162

### CODE REVIEW

**Comment by timmygrable** [comment]
test_ccmanager.py is failing CI build. Looking at slack, it seems to be known and a solution is being worked on.

**Review by ajkerrigan — APPROVED** [review]
Thanks, looks good to me :+1:

**Comment by timmygrable** [comment]
After working to recreate the issue again, it turns out the exact cause is a subnet/VPC that doesn't exist anymore being on the resource. Additionally, when there is more than 1 resource, the policy run succeeds. I was only able to recreate it when there was 1 resource in glue-connection

**Comment by ajkerrigan** [comment]
> After working to recreate the issue again, it turns out the exact cause is a subnet/VPC that doesn't exist anymore being on the resource. Additionally, when there is more than 1 resource, the policy run succeeds. I was only able to recreate it when there was 1 resource in glue-connection. This change resolves this error, and was covered in the unit test added.

Thanks for confirming the issue, fixing it and adding tests :heart:

**Pull request merged**
