### PR TITLE
Add a link to community events to aid with discoverability

### PR DESCRIPTION
**Pull request by castrojo**

### CODE REVIEW

**Comment by kapilt** [comment]
let's fold this into #6887

**Comment by marcoceppi** [comment]
I'm not sure how we could do that @kapilt that PR is targeting the gh-pages branch directly, this is targeting master. Unless gh-pages is generated in some custom process these will need to be unique PRs

**Comment by castrojo** [comment]
Actually it's better to update the URL to the new events page, better to have everything pointing there directly, pushed.

**Review by kapilt — APPROVED** [review]
thanks, lgtm

**Pull request merged**
