### PR TITLE
Plugin dependency validation fix

### PR DESCRIPTION
**Pull request by jondavidi**
fix for https://github.com/cloud-custodian/cloud-custodian/issues/4926
- bug fix
- updates dependencies for azure (partial, still a broken one)
- updates dependencies for kube

HOWEVER.... this bug fix exposes a broken Azure dependency that needs to be addressed before this is merged. I'm not sure if the best way to deal with it. I will say I don't believe that best way to "fix" this issue is to not merge this patch; I believe it's legitimate and needed.

Azure broken dependency described here:
https://github.com/Azure/azure-cosmos-table-python/issues/39
https://github.com/cloud-custodian/cloud-custodian/pull/4325

### CODE REVIEW

**Comment by kapilt** [comment]
using pkg_resources in the runtime is not something we want to do, its expensive and this is a hot path for serverless execution. imo this isn't a runtime concern, its at most a testing one. second this is downgrading kube dependencies. third this per ci this change breaks all usage of custodian due to the conflict in azure-cosmos.

**Comment by slott56** [comment]
How do we resolve the conflict?

**Comment by kapilt** [comment]
we need to get the upstream package to not be published with a broken dependency chain

**Comment by kapilt** [comment]
its been escalated on the azure side, ie. to fix the upstream package deps, but given this breaks ci and usage its unclear thats this pr is suitable  or usable. I'll address the k8s pin in the release pr.

**Pull request closed without merging**
