### PR TITLE
releng - ci add 3.11 remove 3.7

### PR DESCRIPTION
**Pull request by kapilt**
update ci to include python 3.11 and drop python 3.7 (eol upstream end of life imminently)

### CODE REVIEW

**Review by thisisshi — APPROVED** [review]
lgtm, though seems like windows is not happy :/

**Comment by kapilt** [comment]
yeah seems to be an issue with pygit2 on windows when falling back to manual compilation from source, I checked pypi and the latest release has binary window artifacts, was planning on trying to upgrade that one dependency and see if that resolves

**Comment by kentnsw** [comment]
Might be not related to this PR. In my experience, with MacBook Pro M1 chip and Python 3.11, `make install-poetry` failed.
```
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for yarl
  Failed to build yarl
  ERROR: Could not build wheels for yarl, which is required to install pyproject.toml-based projects
```
Yet with Python 3.10, everything is fine.

**Comment by kapilt** [comment]
> Might be not related to this PR. In my experience, with MacBook Pro M1 chip and Python 3.11, `make install-poetry` failed.
> 
> ```
>     note: This error originates from a subprocess, and is likely not a problem with pip.
>     ERROR: Failed building wheel for yarl
>   Failed to build yarl
>   ERROR: Could not build wheels for yarl, which is required to install pyproject.toml-based projects
> ```
> 
> Yet with Python 3.10, or MacBook Pro intel chip + Python 3.11, everything is fine.

Hmm..  this might have been historical and resolved via an update, I noticed on my m1 mac I was using a python 3.10 virtualenv, but I just switched it to a python 3.11.1 virtualenv (and poetry 1.3.2) and `make install-poetry` worked out of the box.

**Pull request merged**
