### PR TITLE
updating ecs insights

### PR DESCRIPTION
**Pull request by femio27**

### CODE REVIEW

**Comment by kapilt** [comment]
Why?

**Comment by femio27** [comment]
@kapilt I keep getting daily failure on Docker build so I was trying to see if that will resolve it

**Comment by kapilt** [comment]
@femio27 daily failure? could you elaborate how your building and what failure your seeing? we build public `:dev` docker images nightly, and I'm not seeing any issues relating to that.

**Comment by thisisshi** [comment]
@femio27 that's not related to this test, your fork doesn't has user/password for dockerhub which causes the publish to fail

**Pull request closed without merging**
