### PR TITLE
fix: update pyyaml to fix upstream install issue

### PR DESCRIPTION
**Pull request by johnsca**
An issue between PyYAML 6.0.0 and an update to Cython broke the ability to install.

Fixes: #8745

### CODE REVIEW

**Comment by kapilt** [comment]
this is superfluous afaics, as we go to update botocore for the next release, we pick up a version with the fix, without that version, there is no fix.

**Comment by kapilt** [comment]
it does seem to update the lock file which seems good to reference 6.0.1, its a little unclear why ci has no issues sans it

**Comment by johnsca** [comment]
Ah, yeah, you're right. The existing constraint in `pyproject.toml` should already allow for 6.0.1 so yeah, it should be superfluous.

**Comment by ajkerrigan** [comment]
Thanks @johnsca , it does seems good to get pyyaml 6.0.1 locked ahead of release, since I believe we add frozen dependency version info to our wheel metadata based on whatever's in poetry.lock at release time.

Separately, looks like this upgrade ran with poetry 1.5.2 so the delta on `poetry.lock` shows removing a bunch of `category` lines :monocle_face: . We've got some poetry 1.4.0 assumptions ([here](https://github.com/cloud-custodian/cloud-custodian/blob/2472bfaa5bb26ecec67e2da7c990ad57da3ce4d1/.github/composites/install/action.yaml#L6-L7) and [here](https://github.com/cloud-custodian/cloud-custodian/blob/2472bfaa5bb26ecec67e2da7c990ad57da3ce4d1/tools/dev/dockerpkg.py#L68) for example), so we may need to either use 1.4.0 to bump lockfiles or bump our other defaults to 1.5.2 to match.

**Comment by johnsca** [comment]
Yeah, I'm closing this because I think it will be unnecessary and 6.0.1 will be used automatically when the next release wheel is built.

**Comment by kapilt** [comment]
pyyaml gets referenced in many of the other package lock files, it would be better to update the whole set per #8747

**Pull request closed without merging**
