### PR TITLE
releng - consolidate mailer dependencies

### PR DESCRIPTION
**Pull request by ajkerrigan**
Part of the issue with #8488 is that having optional/extra dependencies that we freeze for release _but also_ install from a local path at dev time is tricky.

We worked around this using the now-defunct `tools/dev/poetrypkg.py` script by defining gcp/azure dependencies twice - once as path-based dependencies at dev time and once as any-version dependencies for publishing. `pyproject.toml` snippet:

```toml
[tool.poetry.dependencies]
# ...other dependencies...

# Optional packages for additional provider support
c7n-gcp = { version = "*", optional = true }
google-cloud-secret-manager = { version = "^2.8.0", optional = true }
c7n-azure = { version = "*", optional = true }

[tool.poetry.group.dev.dependencies]
# ...other dev dependencies...

c7n-gcp = { path = "../c7n_gcp/", develop = true, optional = true }
c7n-azure = { path = "../c7n_azure/", develop = true, optional = true }
```

That allowed:
- `poetry install` to install c7n-gcp and c7n-azure in develop mode with a local path
- `poetrypkg.py` to freeze the latest available version into built wheels

Without:
- Including the whole gcp/azure dep trees in mailer's wheel
- Locking conflicting versions

But it was still a bit awkward. It looks like moving to the [freeze-wheel plugin](https://github.com/cloud-custodian/poetry-plugin-freeze) is running into the same awkwardness from a different angle.

I'm not sure about the best fix. But [Poetry says](https://python-poetry.org/docs/pyproject/#extras) that you're not allowed to have extras that are part of dependency groups:

> The dependencies specified for each extra must already be defined as project dependencies.
> Dependencies listed in [dependency groups](https://python-poetry.org/docs/managing-dependencies/#dependency-groups) cannot be specified as extras.

So it may be worth trying to specify our extras as optional _main_ dependencies and work out the rest in the freeze-wheel plugin :thinking: 

```toml
[tool.poetry.dependencies]
# ...regular dependencies...

# Optional packages for additional provider support
c7n-gcp = { path = "../c7n_gcp/", develop = true, optional = true }
c7n-azure = { path = "../c7n_azure/", develop = true, optional = true }

[tool.poetry.group.dev.dependencies]
# ...no gcp/azure bits here...
```

### CODE REVIEW

**Comment by kapilt** [comment]
afaics this means these dependencies would get omitted in the built wheel, afaics what we want is to move them to a different group then dev.

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Comment by kapilt** [comment]
we do retain an oddity in that the built wheel METADATA as it denotes an extra for azure and gcp but doesn't have the install dependencies for them.

**Comment by ajkerrigan** [comment]
> we do retain an oddity in that the built wheel METADATA as it denotes an extra for azure and gcp but doesn't have the install dependencies for them.

For sure - I've opened https://github.com/cloud-custodian/poetry-plugin-freeze/pull/11 to address how the freeze-wheel plugin handles nested dependencies with extras. I'm reasonably confident that it gets the freezing to do what we want ([here's](https://github.com/cloud-custodian/cloud-custodian/issues/8488#issuecomment-1508800658) a diff showing how it affects mailer METADATA), but I wouldn't be surprised at all if there was a simpler or more obvious way to get there. If so, at least the added extras-focused test case should be useful.

**Pull request merged**
