### PR TITLE
Include c7n awscc in image

### PR DESCRIPTION
**Pull request by syed-awais-ali**
Addressing the issue https://github.com/cloud-custodian/cloud-custodian/issues/9417

### CODE REVIEW

**Review by kapilt — COMMENTED** [review]
cool, we should also regenerate the docker images, but lgtm on the python changes.

**Comment by kapilt** [comment]
its a makefile target on generating the docker files from using the script (`make geo-docker`), its manual atm for the run, thanks for the pr.

**Comment by awais-ezo** [comment]
@kapilt can I get a review please, thanks !!

**Review by kapilt — APPROVED** [review]
thanks, lgtm

**Pull request merged**
