### PR TITLE
gcp - gke-cluster - fix augment when gke is not enabled

### PR DESCRIPTION
**Pull request by thisisshi**
closes: https://github.com/cloud-custodian/cloud-custodian/issues/8055

### CODE REVIEW

**Review by kapilt — APPROVED** [review]
lgtm, although worth looking at why the query returns a None versus an empty list

**Comment by chase-replicated** [comment]
Any update on this? Seems like it was approved 3 weeks ago, are we just waiting on people to return from the holidays?

**Comment by thisisshi** [comment]
@kapilt could you bypass the codecov check on this

**Comment by kapilt** [comment]
ack, as soon as ci finishes.

**Pull request merged**
