### PR TITLE
Fix a defect where Tag filters don't work on IAM Profiles

### PR DESCRIPTION
**Pull request by dmcguire81**
Addresses defect documented in #7170.

### CODE REVIEW

**Comment by ajkerrigan** [comment]
Thanks @dmcguire81, good catch with the issue and appreciate you submitting a fix! Could you please click through that EasyCLA check above so that we can accept your contribution?

**Review by ajkerrigan — CHANGES_REQUESTED** [review]
Suggested tweak inline to use the bulk tagging API, in an attempt to avoid hitting rate limits.

**Comment by dmcguire81** [comment]
> Thanks @dmcguire81, good catch with the issue and appreciate you submitting a fix! Could you please click through that EasyCLA check above so that we can accept your contribution?

I have a request out to the CLA manager responsible at Blackberry Cylance.

**Comment by dmcguire81** [comment]
> > Thanks @dmcguire81, good catch with the issue and appreciate you submitting a fix! Could you please click through that EasyCLA check above so that we can accept your contribution?
> 
> I have a request out to the CLA manager responsible at Blackberry Cylance.

I can't track down anyone who is willing to act as a CLA manager at Blackberry Cylance, so I'm closing this PR.

**Pull request closed without merging**
