### PR TITLE
Docs - Add example to AWS Tag Action

### PR DESCRIPTION
**Pull request by trastle**
Docs only - Add an example to the docs block of the AWS tag action.

### CODE REVIEW

**Comment by trastle** [comment]
@kapilt should I open an Issue to discuss contributing to the docs for this? 
I can't quite tell from the contributor guide if an Issue is needed for trivial changes like this.

**Comment by kapilt** [comment]
> @kapilt should I open an Issue to discuss contributing to the docs for this?
> I can't quite tell from the contributor guide if an Issue is needed for trivial changes like this.

nope not needed for doc updates, or minor bug fixes.  thanks for the pr!

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Comment by trastle** [comment]
Thanks for the review and merge :-)

**Pull request merged**
