### PR TITLE
azure - sqlserver - add auditing filter

### PR DESCRIPTION
**Pull request by sshearn**

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks for the pull request! Could you please sign the Linux Foundation/CNCF CLA referenced in the other comment. Direct link https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/14202841/52837350/7664/#/?version=2

**Review by thisisshi — APPROVED** [review]
thanks, lgtm

**Comment by thisisshi** [comment]
@sshearn looks like there's a conflict in the tests, could you resolve?

**Comment by sshearn** [comment]
> @sshearn looks like there's a conflict in the tests, could you resolve?

done

**Pull request merged**
