### PR TITLE
azure - validate function name

### PR DESCRIPTION
**Pull request by omusavi**
Add a utility function that checks for a valid function name, replacing invalid characters or throwing an error in the case where it is too short/long. Use this utility function when provisioning a function both in custodian cli and c7n_mailer. Also adds tests for the function and usages

Re: #2634

### CODE REVIEW

**Comment by thisisshi** [comment]
Awesome, we should also add some validations for the AWS Lambda based policies as well, specifically around policy/function name length
On Jan 10, 2019, 7:56 PM -0500, Kapil Thangavelu <notifications@github.com>, wrote:

@kapilt commented on this pull request.

very nice, thanks

**Comment by kapilt** [comment]
@thisisshi the easiest place to do the restrictions would be via jsonschema on the policy name, afaicr, I put some restrictions in there from the get go, but nothing wrt to length size. I'd be a bit concerned about a retrofit there without some consideration of extant policies and compatibility.

**Comment by thisisshi** [comment]
@kapilt opening a separate issue for this: #3352

wrt breaking backwards compatibility, policies of length greater than 64 - prefix fail to deploy anyway, in this case it doesn't seem to be a breaking change, we can move the discussion over to that issue

**Comment by aluong** [comment]
LGTM. (minor refactor we spoke about offline)

**Comment by omusavi** [comment]
Thanks @kapilt for the comments, the PR is updated with a distinction between generating the function name and validating it!

**Pull request merged**
