### PR TITLE
fix: prevent index error when trying to get account from non-arn

### PR DESCRIPTION
**Pull request by cguardia**
Just making sure that if we reach the split statement, it's because it's going to work.

### CODE REVIEW

**Comment by kapilt** [comment]
this needs clarity either in the description or the form of a unit test of what its checking and where the situation arose,. ie what sort of non arn value is it guarding against?

**Comment by cguardia** [comment]
@kapilt we  are getting an IndexError with non-account principals of the form "<uid>::ae-monitor-service-ae-prod-monitor-emr". We've got thousands of these errors, so looking for a way to eliminate them.

**Comment by cguardia** [comment]
Turns out this is related to (and would close) this bug: https://github.com/cloud-custodian/cloud-custodian/issues/6255

**Review by kapilt — APPROVED** [review]
lgtm

**Pull request merged**
