### PR TITLE
Fix for ModuleNotFoundError No module named 'jsonpointer' 

### PR DESCRIPTION
**Pull request by amitsehgal**

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks for the pull request!  If you don't mind could you sign the CLA per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by rficcaglia** [comment]
created GHI to track:
https://github.com/cloud-custodian/cloud-custodian/issues/5707

**Comment by kapilt** [comment]
closing this in favor of #5708 

the file thats being modified here is generated, and isn't related to what gets installed via pip install from pypi

**Comment by amitsehgal** [comment]
signed

**Pull request closed without merging**
