### PR TITLE
c7n_autodoc - automated policy documentation

### PR DESCRIPTION
**Pull request by ryanash999**
This is a simple tool to create an html file which can provide easy to read policy documentation for your business partners.

### CODE REVIEW

**Comment by kapilt** [comment]
awesome, thanks for contributing one of these, its been on the todo list for a while. I think there's alot of these floating around in house in different orgs, but its nice to have a default one in the repo.

If you don't mind could you sign the CLA at the bottom of the README? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by ryanash999** [comment]
Will do.  Gotta have our "process folks" review it.  Hopefully I can get it
done quickly.

**Comment by ryanash999** [comment]
Kapil,
Our support folks are saying we (state farm) have already signed the
corporate CLA.  Will that suffice or is there additional steps we need to
take?

Let me know
Ryan

**Comment by kapilt** [comment]
hi ryan, thanks for verifying, the only additional request would be contributors signing the individual cla as well. direct link https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by ryanash999** [comment]
individual form done too.

**Pull request merged**
