### PR TITLE
add cfn_type to rds-snapshot, redshift-snapshot and elastic-ip

### PR DESCRIPTION
**Pull request by raghavendarreddyg**
This resolves the error ` error: policy:%s resource:%s does not have a cloudformation type` for the resources: rds-snapshot, redshift-snapshot and elastic-ip

### CODE REVIEW

**Comment by thisisshi** [comment]
Hi, thanks for the contribution, looks like this is your first contribution. Could you please take a look at and sign the CLA linked above? Direct link here: https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/14202841/52837350/7664/#/?version=2 Thank you!

**Comment by raghavendarreddyg** [comment]
> Hi, thanks for the contribution, looks like this is your first contribution. Could you please take a look at and sign the CLA linked above? Direct link here: https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/14202841/52837350/7664/#/?version=2 Thank you!

Done

**Comment by raghavendarreddyg** [comment]
Could you please review this PR? @thisisshi  @ajkerrigan  @kapilt @darrendao

**Review by ajkerrigan — APPROVED** [review]
Thanks for the contribution and for signing the CLA, looks good from here! :+1:

**Pull request merged**
