### PR TITLE
releng - update generated requirements files

### PR DESCRIPTION
**Pull request by ajkerrigan**
- Update generated `requirements.txt` files with the output of `make pkg-gen-requirements` using Poetry 1.1.12.
- Add `importlib-resources` to the c7n_sphinxext pyproject.toml

This may still need a couple tweaks or additions, but these changes were enough to get `tox -e docs` working again at least for me. Looking to get input from others...

Addresses #7097

### CODE REVIEW

**Comment by castrojo** [comment]
Confirming that this PR fixed the build for me, thanks AJ!

**Review by kapilt — APPROVED** [review]
thanks, lgtm

**Comment by kapilt** [comment]
why did c7n_sphinxext need importlib-resources ?

**Comment by ajkerrigan** [comment]
> why did c7n_sphinxext need importlib-resources ?

After re-exporting requirements files, `tox -e docs` still threw this error on `make sphinx`:

```bash
c7n-sphinxext --provider aws --output-dir docs/source/aws/resources --group-by=resource_type.service
Traceback (most recent call last):
  File "/home/aj/code/cloud-custodian/.tox/docs/bin/c7n-sphinxext", line 33, in <module>
    sys.exit(load_entry_point('c7n-sphinxext', 'console_scripts', 'c7n-sphinxext')())
  File "/home/aj/code/cloud-custodian/.tox/docs/bin/c7n-sphinxext", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aj/code/cloud-custodian/tools/c7n_sphinxext/c7n_sphinxext/docgen.py", line 25, in <module>
    from c7n.filters import Filter
  File "/home/aj/code/cloud-custodian/c7n/filters/__init__.py", line 3, in <module>
    from .core import (
  File "/home/aj/code/cloud-custodian/c7n/filters/core.py", line 17, in <module>
    from distutils import version
  File "/home/aj/code/cloud-custodian/.tox/docs/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/aj/code/cloud-custodian/.tox/docs/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/aj/code/cloud-custodian/.tox/docs/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/home/aj/code/cloud-custodian/.tox/docs/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/home/aj/code/cloud-custodian/.tox/docs/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/aj/code/cloud-custodian/.tox/docs/lib/python3.10/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/home/aj/code/cloud-custodian/.tox/docs/lib/python3.10/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/aj/code/cloud-custodian/.tox/docs/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib-resources<6.0.0,>=5.4.0' distribution was not found and is required by c7n-sphinxext
make[1]: *** [docs/Makefile.sphinx:86: html] Error 1
make[1]: Leaving directory '/home/aj/code/cloud-custodian'
make: *** [Makefile:101: sphinx] Error 2
ERROR: InvocationError for command /usr/bin/make sphinx (exited with code 2)
```
Which seemed to be because we specify `importlib-resources` in the `c7n_sphinxext` setup.py [here](https://github.com/cloud-custodian/cloud-custodian/blob/acf4c86583c8e63df9ab4827dd419b5369098365/tools/c7n_sphinxext/setup.py#L24). Maybe we don't need to?

**Pull request merged**
