### PR TITLE
pin dependencies for py27 (#3558)

### PR DESCRIPTION
**Pull request by CMeza99**
Solution proposal to address concern in #3558#issuecomment-584611448

```
❯ pipenv graph

c7n==0.8.46.1.dev19+gf9c9c9f0f.d20200211
  - argcomplete [required: Any, installed: 1.11.1]
    - importlib-metadata [required: >=0.23,<2, installed: 1.5.0]
      - configparser [required: >=3.5, installed: 4.0.2]
      - contextlib2 [required: Any, installed: 0.6.0.post1]
      - pathlib2 [required: Any, installed: 2.3.5]
        - scandir [required: Any, installed: 1.10.0]
        - six [required: Any, installed: 1.14.0]
      - zipp [required: >=0.5, installed: 1.1.0]
        - contextlib2 [required: Any, installed: 0.6.0.post1]
  - backports.functools-lru-cache [required: Any, installed: 1.6.1]
  - boto3 [required: >=1.9.228, installed: 1.11.15]
    - botocore [required: >=1.14.15,<1.15.0, installed: 1.14.15]
      - docutils [required: >=0.10,<0.16, installed: 0.15.2]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
        - six [required: >=1.5, installed: 1.14.0]
      - urllib3 [required: >=1.20,<1.26, installed: 1.25.8]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
    - s3transfer [required: >=0.3.0,<0.4.0, installed: 0.3.3]
      - botocore [required: >=1.12.36,<2.0a.0, installed: 1.14.15]
        - docutils [required: >=0.10,<0.16, installed: 0.15.2]
        - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
        - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
          - six [required: >=1.5, installed: 1.14.0]
        - urllib3 [required: >=1.20,<1.26, installed: 1.25.8]
      - futures [required: >=2.2.0,<4.0.0, installed: 3.3.0]
  - botocore [required: >=1.13.46, installed: 1.14.15]
    - docutils [required: >=0.10,<0.16, installed: 0.15.2]
    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.4]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
      - six [required: >=1.5, installed: 1.14.0]
    - urllib3 [required: >=1.20,<1.26, installed: 1.25.8]
  - certifi [required: Any, installed: 2019.11.28]
  - jsonpatch [required: >=1.21, installed: 1.25]
    - jsonpointer [required: >=1.9, installed: 2.0]
  - jsonschema [required: Any, installed: 3.2.0]
    - attrs [required: >=17.4.0, installed: 19.3.0]
    - functools32 [required: Any, installed: 3.2.3.post2]
    - importlib-metadata [required: Any, installed: 1.5.0]
      - configparser [required: >=3.5, installed: 4.0.2]
      - contextlib2 [required: Any, installed: 0.6.0.post1]
      - pathlib2 [required: Any, installed: 2.3.5]
        - scandir [required: Any, installed: 1.10.0]
        - six [required: Any, installed: 1.14.0]
      - zipp [required: >=0.5, installed: 1.1.0]
        - contextlib2 [required: Any, installed: 0.6.0.post1]
    - pyrsistent [required: >=0.14.0, installed: 0.15.7]
      - six [required: Any, installed: 1.14.0]
    - setuptools [required: Any, installed: 44.0.0]
    - six [required: >=1.11.0, installed: 1.14.0]
  - python-dateutil [required: >=2.6,<3.0.0, installed: 2.8.1]
    - six [required: >=1.5, installed: 1.14.0]
  - PyYAML [required: >=5.1, installed: 5.3]
  - tabulate [required: >=0.8.2, installed: 0.8.6]
  - urllib3 [required: Any, installed: 1.25.8]
```

### CODE REVIEW

**Comment by kapilt** [comment]
thanks, and omg, this is so much simpler, i think i was looking at this all wrong, re building tools for freezing, versus just sticking the static set into metadata. we'll need to do this for c7n_gcp and c7n_azure as well.

**Comment by kapilt** [comment]
also i haven't had a chance to check but if you haven't signed the cla, could you have a look could at CLA per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by kapilt** [comment]
> thanks, and omg, this is so much simpler, i think i was looking at this all wrong, re building tools for freezing, versus just sticking the static set into metadata. we'll need to do this for c7n_gcp and c7n_azure as well.

although we still need those tools for gcp and azure functions where the runtime will server side fetch deps for us, for the use case around py2.7 0.8 last release, this static freeze seems the most expedient, this should be targeting the 0.8 branch though, not master. for master we're looking at moving to poetry and then just generating setup.py/requirements.txt for compatibility from poetry/poetry.lock per wip in #5320 

one other caveat is pip freeze isn't capturing the original requires statements, which may have additional conditionals (sys_platform or python_version constraints), its mostly equivalent to what we're doing already with c7n.mu,generate_requirements, but sans those require constraints,  a pip freeze on 3.7 will have a different output then a pip freeze on 2.7, which is where i was getting into a tangle with #5327 .. its hard even evaluating those constraints, and i timed out looking at requirements parsing that would allow for a cleaner evaluation, we should generally be doing pass through on that, but say we're on python 3.7/3.8 doing a package for 2.7 or 3.6 with a package that has an additional version constraint (or os constraint), we need to query pypi for the version that satisfies that to freeze it, since its not locally installed.

**Comment by kapilt** [comment]
we need this pull-request targeted to the 0.8 release branch, for trunk, we're just going to switch to poetry per #5320  (compatible with setuptools/pip) and drop 2.7 entirely.

**Comment by JohnHillegass** [comment]
Closing as many of these changes have been made is some form on trunk and as of 9.1. Thanks for the contribution though and the other work in https://github.com/cloud-custodian/cloud-custodian/pull/5528 !

**Pull request closed without merging**
