### PR TITLE
Support numbers as days and hours

### LINKED ISSUE #5952: Support minutes in mark-for-op actions
**Is your feature request related to a problem? Please describe.**
`mark-for-op` just supports days and hours. These units are too big for some use cases.

**Describe the solution you'd like**
`mark-for-op` should also support minutes and maybe the other units supported by datetime.timedelta: seconds, microseconds, milliseconds, and weeks.
https://docs.python.org/3/library/datetime.html#datetime.timedelta

**Describe alternatives you've considered**
`mark-for-op` could also accept a float as hours, but this would be more complicated to implement and less reliable.

**Additional context**
```yaml
policies:
- name: ec2-mark-stop
  resource: ec2
  filters:
    - type: image-age
      op: ge
      minutes: 90
  actions:
    - type: mark-for-op
      tag: custodian_cleanup
      op: terminate
      minutes: 4
```

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
Closes #5952

### CODE REVIEW

**Comment by kapilt** [comment]
thanks for the pull request, I've started a discussion on the issue to clarify use case.   If you don't mind could you sign the CLA at per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by t0rr3sp3dr0** [comment]
@kapilt I've already signed the CLA

**Comment by kapilt** [comment]
per issue discussion let's just update hours/days to take a number.

**Comment by t0rr3sp3dr0** [comment]
@kapilt I've made the changes

**Pull request merged**
