### PR TITLE
Add ability to force delete iam role

### PR DESCRIPTION
**Pull request by vauchok**
Hi there,

this is related:
#6340
#6044

I don't think, that we need to create an additional action to add/remove role from instance profile. So I've just added this one.

Thanks,

### CODE REVIEW

**Comment by vauchok** [comment]
Note:
Make sure that you do not have any Amazon EC2 instances running with the role you are about to remove from the instance profile. Removing a role from an instance profile that is associated with a running instance might break any applications running on the instance.

**Comment by vauchok** [comment]
Hi @kapilt, 

Can you look at PR. Any suggestions or remarks?

Thanks.

**Comment by kapilt** [comment]
hi @vauchok looks good, re instance profile behind force option, i was a little unclear if the instance profile is referenced by an extant instance if the deletion was allowed (ie strong reference or weak reference). we probably want to add a line to the class doc for the action re that implication on the force parameter.

**Comment by kapilt** [comment]
i think the ci failure here is unrelated this also showed up in a docs pr update, i'll see if we can get that worked on independent of this.

**Comment by vauchok** [comment]
> i think the ci failure here is unrelated this also showed up in a docs pr update, i'll see if we can get that worked on independent of this.

It looks like everything is good now.

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Pull request merged**
