### PR TITLE
Added azure key vault secret resource

### PR DESCRIPTION
**Pull request by bhavikmck**
Created Azure resource for the Key vault secret

### CODE REVIEW

**Comment by thisisshi** [comment]
Hi, thanks for the contribution, looks like this is your first contribution. Could you please take a look at and sign the CLA linked above? Direct link here: https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/14202841/52837350/7664/#/?version=2 Thank you!

**Comment by dslagle** [comment]
@thisisshi - the CLA has been taken care of, please review when you are able. Thanks!

**Comment by thisisshi** [comment]
could use a test

**Comment by bhavikmck** [comment]
@thisisshi, I have included test cases as requested. PR is ready for review again. Please review it when you can.

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Pull request merged**
