### PR TITLE
Fixing compute disk resource manager class type

### PR DESCRIPTION
**Pull request by raiesmh08**
In current implementation, API being used in Aggregated APIs while scope is zone, which will create an issue while doing disk operations. Fixing API enum specs.

### CODE REVIEW

**Comment by kapilt** [comment]
do you have an example of where this would be an issue? changing from aggregation api to regional would affect existing deploys in that they would be regional targeted. this would need some additional context for extant gcp users as its otherwise a breaking change wrt to extant deployments no longer having visibility into regional disks without explicitly targeting each region.

**Comment by raiesmh08** [comment]
> do you have an example of where this would be an issue? changing from aggregation api to regional would affect existing deploys in that they would be regional targeted. this would need some additional context for extant gcp users as its otherwise a breaking change wrt to extant deployments no longer having visibility into regional disks without explicitly targeting each region.

**Comment by raiesmh08** [comment]
> do you have an example of where this would be an issue? changing from aggregation api to regional would affect existing deploys in that they would be regional targeted. this would need some additional context for extant gcp users as its otherwise a breaking change wrt to extant deployments no longer having visibility into regional disks without explicitly targeting each region.

So basically when I trying to delete disk, I get this error - 
File "/usr/local/lib/python3.12/site-packages/googleapiclient/discovery.py", line 1099, in method
raise TypeError("Got an unexpected keyword argument {}".format(name))
TypeError: Got an unexpected keyword argument zone

When I change enum specs to list than Aggregate API, it works.

**Comment by kapilt** [comment]
you'll have to provide policy and custodian version, I can run a simple policy on gcp disk without issue, so I'm still unclear what this 

```
❯ custodian run gcp-disk.yaml -s out -v --debug
2024-06-25 10:11:31,914: custodian.commands:DEBUG Loaded file gcp-disk.yaml. Contains 1 policies
2024-06-25 10:11:31,915: custodian.output:DEBUG Storing output with <LogFile file://out/check-disk/custodian-run.log>
2024-06-25 10:11:31,915: custodian.policy:DEBUG Running policy:check-disk resource:gcp.disk region:default c7n:0.9.38
2024-06-25 10:11:31,916: google.auth._default:DEBUG Checking None for explicit credentials as part of auth process...
2024-06-25 10:11:31,916: google.auth._default:DEBUG Checking Cloud SDK credentials as part of auth process...
2024-06-25 10:11:32,166: google_auth_httplib2:DEBUG Making request: POST https://oauth2.googleapis.com/token
2024-06-25 10:11:33,010: c7n_gcp.client:DEBUG Executing paged request #1
2024-06-25 10:11:33,014: custodian.resources.disk:DEBUG Filtered from 1 to 1 disk
2024-06-25 10:11:33,015: custodian.policy:INFO policy:check-disk resource:gcp.disk region: count:1 time:1.10
2024-06-25 10:11:33,016: custodian.output:DEBUG metric:ResourceCount Count:1 policy:check-disk restype:gcp.disk scope:policy

src-custodian on  main [$?] is 📦 v0.9.38 via 🐍 v3.12.3 (c7n-3.12) on ☁️  Sandbox-Kapil-Admin (us-east-1) on ☁️  
❯ cat gcp-disk.yaml 
policies:

 - name: check-disk
   resource: gcp.disk

```

**Comment by kapilt** [comment]
closing due to lack of response on request for more details and demonstration of extant working.

**Pull request closed without merging**
