### PR TITLE
release - 0.9.18.0 - prep for release 0.9.18

### PR DESCRIPTION
**Pull request by darrendao**

### CODE REVIEW

**Review by thisisshi — APPROVED** [review]

**Comment by ajkerrigan** [comment]
I opened https://github.com/darrendao/cloud-custodian/pull/1 as a PR to this branch. The dep conflict we hit while prepping this release was due to a transient dependency in `c7n_sphinxext`.

That update also revealed a malformed example policy that is silently broken in docs today, and failed more explicitly on a newer version of `myst-parser`.

**Comment by darrendao** [comment]
@ajkerrigan @thisisshi I've fixed the security hub tests but now there's another test failure that I don't know how to fix. Error message is 

```
______________ PolicyMetaLint.test_resource_shadow_source_augment ______________
[gw0] linux -- Python 3.9.13 /home/runner/work/cloud-custodian/cloud-custodian/.venv/bin/python
Traceback (most recent call last):
  File "/home/runner/work/cloud-custodian/cloud-custodian/tests/test_policy.py", line 1[74](https://github.com/cloud-custodian/cloud-custodian/runs/7753837574?check_suite_focus=true#step:11:75), in test_resource_shadow_source_augment
    self.fail(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/unittest/case.py", line 6[76](https://github.com/cloud-custodian/cloud-custodian/runs/7753837574?check_suite_focus=true#step:11:77), in fail
    raise self.failureException(msg)
AssertionError: workspaces, step-machine, kafka, sagemaker-model have resource managers shadowing source augments
```

It's related to the changes that we made to those resources where we set `cfn_type = config_type = ...`. I'm guessing a resource type can't have both `config_type` and `augment()`?

**Comment by ajkerrigan** [comment]
Ahh yes @darrendao, you got the idea there. `augment` is designed to be source-specific. In this case the fix should be similar to the changes [here](https://github.com/cloud-custodian/cloud-custodian/pull/5408/files#diff-3c65a79fcb94e0c130ebae92854802412ab7f81f977070bc27b56d8615057e29R123-R154), which:

* Move the existing resource-level `augment` to a new describe source
* Define a `source_mapping` for the resource, using the default ConfigSource the newly created describe source

**Review by kapilt — APPROVED** [review]
lgtm

**Pull request merged**
