### PR TITLE
setup codeql scanning

### PR DESCRIPTION
**Pull request by kapilt**
try out codeql scanning

### CODE REVIEW

**Comment by kapilt** [comment]
unfortunately this adds significant latency to ci, it might be worth running on master just to have awareness, but for prs, its feels a bit heavy weight.

**Comment by JohnHillegass** [comment]
Agreed! 12 minutes is definitely a bit heavy. Does it make sense to run right before a release?

**Comment by kapilt** [comment]
I'm thinking we just run it on master commits for now, and leave off on pull requests, its possible that there's some cache knobs that can be tweaked.

**Comment by JohnHillegass** [comment]
Yes, that seems like a reasonable approach too. Maybe we could just comment out the `on: pull_request` and `on: schedule ` parts for now.

**Comment by JohnHillegass** [comment]
Added an update for that, just running on push/merge to master.

**Comment by kapilt** [comment]
we might still want the cron, although if its pure code analysis as opposed to dep its a little unclear what its going to detect if master is unchanged.

**Comment by JohnHillegass** [comment]
Yeah, I agree with using cron if it was dep analysis but my impression is the CodeQL tool is only looking for patterns of vulnerabilities in the repository source. I believe the security advisories would cover us on dep vulnerabilities.

**Comment by kapilt** [comment]
i think we need a deeper dive on the configurations options here before we can pr this

**Comment by JohnHillegass** [comment]
Good call. I saw there were a few new announcements at GitHub Universe. Probably best to take a step back and review.

**Pull request closed without merging**
