### PR TITLE
c7n-autodoc updates

### PR DESCRIPTION
**Pull request by ryanash999**
Several updates to c7n-autodoc improve usability.  
- UI updates to add some simple javascript accordion functionality for easier policy browsing
- Update backend python to only require a single yml file as input for all configurations

### CODE REVIEW

**Comment by kapilt** [comment]
can you target this pr to the current location in sandbox? ie base the pr on trunk

**Comment by kapilt** [comment]
actually it looks like this pr has the changes to the sandbox directory, but its also carrying changes for the original location as well.

**Comment by kapilt** [comment]
Pushed a minor cleanup, the changes look great, re moving the configuration to a file with validation.

**Comment by ryanash999** [comment]
Do you still need me to modify this PR?  I'm happy to make adjustments as needed, it just may take me a bit...dealing with other issues.  thx

**Pull request merged**
