### PR TITLE
core - recreate cache connection as needed

### PR DESCRIPTION
**Pull request by ajkerrigan**
I started hitting new errors with caching while testing #7684 (`sqlite3.ProgrammingError: Cannot operate on a closed database.` when trying to save to the cache). Tweaked the cache connection logic to work around them while trying to keep the original spirit. There may be a cleaner/better way to do this. Core changes:

- Recreate a sqlite connection if one hasn't been created yet, or if the existing one was closed
- Keep the previous intention of "only calling `load()` once" by caching that method

### CODE REVIEW

**Comment by kapilt** [comment]
Do you have trace backs, we set conn to none when closing which makes SQLite closed errors seems a bit odd.

**Comment by ajkerrigan** [comment]
> Do you have trace backs, we set conn to none when closing which makes SQLite closed errors seems a bit odd.

True, my bad the first error I hit was another `AttributeError: __enter__` during save:

```
Traceback (most recent call last):
  File "/home/aj/code/cloud-custodian/c7n/commands.py", line 302, in run
    policy()
  File "/home/aj/code/cloud-custodian/c7n/policy.py", line 1281, in __call__
    resources = PullMode(self).run()
  File "/home/aj/code/cloud-custodian/c7n/policy.py", line 294, in run
    resources = self.policy.resource_manager.resources()
  File "/home/aj/code/cloud-custodian/c7n/query.py", line 535, in resources
    resources = self.filter_resources(resources)
  File "/home/aj/code/cloud-custodian/c7n/manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "/home/aj/code/cloud-custodian/c7n/filters/core.py", line 553, in process
    return super(ValueFilter, self).process(resources, event)
  File "/home/aj/code/cloud-custodian/c7n/filters/core.py", line 190, in process
    return list(filter(self, resources))
  File "/home/aj/code/cloud-custodian/c7n/filters/core.py", line 540, in __call__
    matched = self.match(i)
  File "/home/aj/code/cloud-custodian/c7n/filters/core.py", line 566, in match
    self.v = values.get_values()
  File "/home/aj/code/cloud-custodian/c7n/resolver.py", line 157, in get_values
    self.cache.save(("value-from", key), contents)
  File "/home/aj/code/cloud-custodian/c7n/cache.py", line 158, in save
    with self.conn as cursor:
AttributeError: __enter__
```

The `ProgrammingError` came from my first attempt at a workaround, caching that connection to keep it around for the whole policy run. That didn't work because we potentially close and recreate the connection multiple times per execution. Figured caching the response from `load()` and having a liveness check on the connection might make sense.

**Comment by kapilt** [comment]
Could you clarify on the policy here, because afaics this was what was fixed either last pr on Sqlkv cache

**Comment by kapilt** [comment]
I’m trying to create a forcing function to closing connections (and erroring if not, perhaps more explicitly On cause) and tracking them, the alternative that’s viable is forcing all uses of cache into context manager. There’s a whole slew of SQLite multi thread issues we’re trying to avoid and auto-open feels like it will compound those.

**Comment by ajkerrigan** [comment]
That's fair, yeah I'm really not sure about the best answer myself. But as far as error reproduction goes...

Sample policy:

```yaml
policies:
  - name: sqs-metrics
    resource: aws.sqs
    filters:
      - type: value
        key: tag:Owner
        op: in
        value_from:
            url: s3://my_bucket/valid_tags.json
            format: json
            expr: 'Owner[]'
```

And you're right, the last fix PR helped. It's still blowing up inside `c7n.resolver.ValuesFrom.get_values()`, but before the PR it was dying [on the get](https://github.com/cloud-custodian/cloud-custodian/blob/a88b467395702173fbdd35f018b716879aa93a1a/c7n/resolver.py#L151) and afterward it started dying [on the save](https://github.com/cloud-custodian/cloud-custodian/blob/a88b467395702173fbdd35f018b716879aa93a1a/c7n/resolver.py#L157). Looked like it was because in between the cache get and cache save, we call [`contents = self._get_values()`](https://github.com/cloud-custodian/cloud-custodian/blob/a88b467395702173fbdd35f018b716879aa93a1a/c7n/resolver.py#L155) which goes `get_contents()` --> `resolve()` which closes the connection and sets it to `None`.

**Comment by ajkerrigan** [comment]
Closing this in favor of an issue, since the direction of this PR seems wrong but tracking is still useful.

**Pull request closed without merging**
