### PR TITLE
docs - readme c7n-org spelling and syntax changes

### PR DESCRIPTION
**Pull request by bartgonzalez**
Updated grammar/punctuation around variable interpolation note and small punctuation changes throughout the c7n-org readme. 

[update removed closing issue reference]

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks for the pr, *Please* don't reference closing issues when making spelling and syntax doc fixes, its unrelated to the issue.

**Comment by kapilt** [comment]
We might need a separate docs branch for the sprint

**Comment by kapilt** [comment]
can you retarget this to the docs-sprint branch

**Comment by bartgonzalez** [comment]
Thanks for the feedback! Retargeted to docs-sprint.

**Pull request merged**
