### PR TITLE
aws - ec2 svc id prefix for more resources

### PR DESCRIPTION
**Pull request by kapilt**
multi resource events (ala create tags), need an id_prefix 
distinction for disambiguation.
﻿

### CODE REVIEW

**Comment by JohnHillegass** [comment]
Should we also add sg- for security group and subnet- ?

**Review by JohnHillegass — APPROVED** [review]
lgtm!

**Comment by JohnHillegass** [comment]
@kapilt what do you think about adding some more docs around event pattern matching? Was recently playing with something like this to only invoke on changes to certain tags.

```
      - name: detect-changes-to-only-certain-tags
        resource: aws.subnet
        mode:
          type: cloudtrail
          role: CustodianDemoRole
          events:
            - source: ec2.amazonaws.com
              event: CreateTags
              ids: requestParameters.resourcesSet.items[].resourceId
            - source: ec2.amazonaws.com
              event: DeleteTags
              ids: requestParameters.resourcesSet.items[].resourceId
          pattern:
            detail:
              requestParameters:
                resourcesSet:
                  items:
                    resourceId:
                      - prefix: sg-
                tagSet:
                  items:
                    key:
                      - prefix: c7n-
                      - MyTag
```

**Comment by kapilt** [comment]
additional pattern event matching in docs around cloud trail mode sounds
good. docs are generally good as a rule :-)

**Pull request merged**
