### PR TITLE
Tidy up the go.mod for cask.

### PR DESCRIPTION
**Pull request by howbazaar**
Just ran 'go mod tidy' for tools/cask.

It has seemed to pick up more dependencies, and remove some unneeded ones.

### CODE REVIEW

**Comment by kapilt** [comment]
looks good, but i'm curious where the protobuf and airbreak transitive deps are coming in, any tool you'd recommend for dep graph exploration on golang?

**Comment by howbazaar** [comment]
The godoc site used to have a dependency graph at the bottom, let me see if I can find one.

**Comment by howbazaar** [comment]
Found 'go mod graph' which gives a line by line break down of the dependencies. However that wasn't as useful as I thought.

```sh
❯ go mod why gopkg.in/airbrake/gobrake.v2
# gopkg.in/airbrake/gobrake.v2
github.com/cloud-custodian/cloud-custodian/tools/cask
github.com/docker/docker/pkg/jsonmessage
github.com/docker/docker/pkg/term
github.com/docker/docker/pkg/term/windows
github.com/Sirupsen/logrus
github.com/Sirupsen/logrus.test
gopkg.in/gemnasium/logrus-airbrake-hook.v2
gopkg.in/airbrake/gobrake.v2
```

`go mod graph` will show that the protobuf imports come from `github.com/onsi/ginkgo`.

```sh
❯ go mod why github.com/onsi/ginkgo
# github.com/onsi/ginkgo
github.com/cloud-custodian/cloud-custodian/tools/cask
github.com/docker/docker/pkg/jsonmessage
github.com/docker/docker/pkg/term
github.com/docker/docker/pkg/term/windows
github.com/Sirupsen/logrus
github.com/Sirupsen/logrus.test
gopkg.in/gemnasium/logrus-airbrake-hook.v2
gopkg.in/airbrake/gobrake.v2
gopkg.in/airbrake/gobrake.v2.test
github.com/onsi/ginkgo
```
The reason we see all the `// indirect` lines in `go.mod` is because the `github.com/docker/docker` does not use go.mod.

**Review by kapilt — APPROVED** [review]
thanks, lgtm

**Pull request merged**
