### PR TITLE
azure - advisor (cloud-custodian#6836)

### PR DESCRIPTION
**Pull request by lkakarla**

### CODE REVIEW

**Review by logachev — APPROVED** [review]
lgtm, will figure out what was wrong with Docker build since it has to be unrelated to the change.

**Comment by logachev** [comment]
@lkakarla it seems like poetry.lock file is not up to date.. Can you add it to the PR? (changing toml file is not enough)

**Comment by lkakarla** [comment]
@logachev I updated poetry.lock file with dependencies

**Comment by logachev** [comment]
@lkakarla Thank you!

**Pull request merged**
