### PR TITLE
Enable Sendgrid for AWS

### PR DESCRIPTION
**Pull request by zscholl**
This addresses #2388.

The change allows you to supply a KMS encrypted Sendgrid API token in `mailer.yaml` like so:

```yaml
queue_url: https://sqs.us-west-2.amazonaws.com/123456789012/some-queue
role: arn:aws:iam::123456789012:role/SomeRole
from_address: no-reply-cloudcustodian@mydomain.com
region: us-west-2
ses_region: us-west-2
sendgrid_api_key: AGUij314...
```

You can then deploy the mailer as a lambda and it will send your notifications via sendgrid.

`c7n-mailer --config my_mailer_conf.yaml --update-lambda`

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks for the pull request!  If you don't mind could you sign the CLA per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by zscholl** [comment]
> Thanks for the pull request! If you don't mind could you sign the CLA per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

Hey @kapilt, I should be on the Corporate agreement for Zendesk. Our legal department just recently confirmed that it should be signed but I can follow up if you don't have it on your end.

**Comment by kapilt** [comment]
> Hey @kapilt, I should be on the Corporate agreement for Zendesk. Our legal department just recently confirmed that it should be signed but I can follow up if you don't have it on your end.

thanks, we generally ask that folks also sign the individual cla, as the corporate entries are static and team membership changes, additionally the community maintainers (of which i'm one) only have access to the icla signatures.

**Comment by zscholl** [comment]
> thanks, we generally ask that folks also sign the individual cla, as the corporate entries are static and team membership changes, additionally the community maintainers (of which i'm one) only have access to the icla signatures.

Roger that, makes sense. I've submitted the individual agreement

**Pull request merged**
