### PR TITLE
aws.asg - handle missing launch template parameters

### PR DESCRIPTION
**Pull request by thisisshi**
There are some hard references to the BlockDeviceMappings attribute that is present in launch configurations but not launch templates. Still testing other scenarios here, looks like the ConfigValid and NotEncrypted filters are affected at the very least

```
Traceback (most recent call last):
File "/src/c7n/policy.py", line 232, in run
resources = self.policy.resource_manager.resources()
File "/src/c7n/query.py", line 421, in resources
resources = self.filter_resources(resources)
File "/src/c7n/manager.py", line 105, in filter_resources
resources = f.process(resources, event)
File "/src/c7n/resources/asg.py", line 464, in process
self.unencrypted_launch = self.get_unencrypted_configs()
File "/src/c7n/resources/asg.py", line 511, in get_unencrypted_configs
for bd in c['BlockDeviceMappings']:
KeyError: 'BlockDeviceMappings'
```

### CODE REVIEW

**Comment by kapilt** [comment]
launch templates do have block device mappings [0], although perhaps not mandatory, perhaps rather than doing piecemeal merges like the #3252 it would be good to get something end to end verified first.
[0] -https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_launch_template_versions

**Comment by thisisshi** [comment]
Yup, I’ll be doing a deeper dive on this tomorrow

**Comment by thisisshi** [comment]
looks like parameters are optional when creating launch templates:

>Launch parameters are optional. However, you must ensure that your request to launch an instance includes all required parameters. For example, if your launch template does not include an AMI ID, you must specify both the launch template and an AMI ID when you launch an instance.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html

**Comment by thisisshi** [comment]
actually, it looks like ImageId might be required but not documented, in ec2 you can override the launch template's image id by passing in one directly to the run_instances call but I don't see a place where that's supported in the create_auto_scaling_group api.

note: when trying to create an asg through the console with an imageless launch template it fails on validation

**Comment by thisisshi** [comment]
took a finer look at all the places where LaunchInfo objects are instantiated and backfilled some tests to prove out the functionality for them, I'm not entirely sure if we need the test as they don't really prove out any additional functionality, but it does provide some launch templates with very minimal configuration. In particular the ConfigValid and NotEncrypted filter had a lot of references to attributes on the launch configuration dict, the image-age/image tests are probably fine to drop, given my comments above about image id being mandatory (even though the documentation would tell you otherwise)

**Comment by kapilt** [comment]
re imageid, its probably in reference to other contexts where launch templates can be used. at least with straight ec2, i think you can override any template ref.

**Pull request merged**
