### PR TITLE
aws - security hub - isoformat is erroring out on date formats ( post-findings) action, removing conversion is working fine

### PR DESCRIPTION
**Pull request by amitsehgal**
addresses #6171

### CODE REVIEW

**Comment by kapilt** [comment]
which version of the boto sdk are you using? (custodian version --debug | grep boto)

**Comment by amitsehgal** [comment]
custodian version --debug | grep boto
boto3==1.14.57
botocore==1.17.57

**Comment by amitsehgal** [comment]
@kapilt Shall I proceed with fixes (fixing test cases) for this issue ? or boto3 upgrade may help... i haven't tried it yet.. looks like, i do have boto3 configured for 0.9.4/0.9.6

**Comment by kapilt** [comment]
going through your posted issue #6171  is specific to config rule mode afaics, and we'll need to normalize the behavior when converting from config's idiosyncratic formatting. when doing a describe on the resources in question, the results are as a date time object. config generally does random mangling of resources attributes to its own format.

**Comment by kapilt** [comment]
i don't really see a good option here outside of moving to implicit date time conversion via key name sniffing when normalizing config's format to describe

**Comment by kapilt** [comment]
superceded by a better fix in #6181

**Pull request closed without merging**
