### PR TITLE
openstack - Add OpenStack Provider (#6316)

### PR DESCRIPTION
**Pull request by int32bit**
Add OpenStack Provider with some filters, we will add more filters and actions later.

### CODE REVIEW

**Comment by kapilt** [comment]
oh wow, thanks!, this looks great!. i'm going to have setup an openstack install to kick the tires.

**Comment by kapilt** [comment]
just wanted to update, that I've got a [microstack](https://microstack.run) open stack up and running to try this out against.

**Comment by int32bit** [comment]
As Microstack will not auto generate openrc, I use follow script to initialize c7n configuration:

```
echo '!env | grep OS_' | microstack.openstack | grep -v '^$' | sed 's/^/export &/g' >openrc
source openrc
```

**Review by kapilt — APPROVED** [review]
lgtm, thanks, this pr is pretty awesome! we'll need to work out some project resources for testing this regularly but we can do that post merge.

**Pull request merged**
