### PR TITLE
releng - directly publish docs instead of merging back to gh-pages branch

### PR DESCRIPTION
**Pull request by kapilt**
addresses #8136

instead of building up hundreds of mbs of generated ref docs and commiting back to gh pages, instead
directly publish the build output to the docs website.

### CODE REVIEW

**Review by ajkerrigan — COMMENTED** [review]
Nice, certainly more straightforward :sunglasses: . One question - do we need to add a `permissions` block to [the `Docs` job](https://github.com/cloud-custodian/cloud-custodian/blob/bdda464c47fdb60a652d19194fa298a5e41cad32/.github/workflows/ci-main.yml#L52-L54) so it has access to the OIDC creds?

This is yoinked from the [configure-aws-credentials usage docs](https://github.com/aws-actions/configure-aws-credentials#usage):

```yaml
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
```

**Comment by kapilt** [comment]
> Nice, certainly more straightforward 😎 . One question - do we need to add a `permissions` block to [the `Docs` job](https://github.com/cloud-custodian/cloud-custodian/blob/bdda464c47fdb60a652d19194fa298a5e41cad32/.github/workflows/ci-main.yml#L52-L54) so it has access to the OIDC creds?
> 
> This is yoinked from the [configure-aws-credentials usage docs](https://github.com/aws-actions/configure-aws-credentials#usage):
> 
> ```yaml
>     # These permissions are needed to interact with GitHub's OIDC Token endpoint.
>     permissions:
>       id-token: write
>       contents: read
> ```

we do thanks

**Review by ajkerrigan — APPROVED** [review]
lgtm :+1:

**Comment by kapilt** [comment]
doh wasn't quite ready to merge yet

**Comment by thisisshi** [comment]
yea my bad, just saw the slack thread after i hit merge :facepalm:

**Pull request merged**
