### PR TITLE
Get ASG image info instead of just image ID

### PR DESCRIPTION
**Pull request by tim-elliott**
Proposed solution for https://github.com/cloud-custodian/cloud-custodian/issues/6038

### CODE REVIEW

**Comment by JohnHillegass** [comment]
Looks good @tim-elliott, though is there a way to minimize the test recording sizes? You may have an opportunity to get rid of some of the matches in the json. For example in the images or launch configurations, could we get away with just having one result in the array?

**Comment by kapilt** [comment]
thanks for adding a test tim, per john's comment we'll want to manually trim down the recorded data by minimizing the duplication, fyi using source: config and a query filter to do a server side filter by resourceId allows for some of this in a more automated fashion.

**Comment by tim-elliott** [comment]
@JohnHillegass It was actually a deliberate choice to have multiple, different matches in the test data to validate the differentiates between the various data sources.  I can reduce the test data if that is the project preference.

**Comment by tim-elliott** [comment]
Test data has been reduced, I'll cut more if needed but would like to have enough data to have the opportunity to fail with a larger number than expected, and not just failure on 0 instead of 1.

**Pull request merged**
