### PR TITLE
Add 'project-iam-policy' GCP policy to list project IAM policies.

### PR DESCRIPTION
**Pull request by vitali-shcharbin**
Add 'project-iam-policy' GCP policy to list project IAM policies.

### CODE REVIEW

**Comment by kapilt** [comment]
this should be a filter not a resource

**Comment by vitali-shcharbin** [comment]
@kapilt what is resource should be used in this case? I could find project IAM policy resource

**Comment by kapilt** [comment]
there are many resources with iam policies, common usage idiom is to use a generic filter and action for them across those resources. not exposing dozen of iam policy child resources.

**Comment by vitali-shcharbin** [comment]
@kapilt sure, that what I'm trying to achieve, I need to check KMS policy, so I created common resource    'project-iam-policy'  that could be used to check policies for various resources.

**Comment by kapilt** [comment]
the iam policy filter is common to many resources not a policy project resource (child resource).

**Pull request closed without merging**
