### PR TITLE
aws - kinesis - add force parameter for deleting kinesis streams (#7260)

### PR DESCRIPTION
**Pull request by jarylc**
PR for issue #7260

Questions:
- How do I update the documentation at https://cloudcustodian.io/docs/aws/resources/kinesis.html#delete? Found the `gh-pages` branch but are there other steps?

### CODE REVIEW

**Comment by jarylc** [comment]
Ah, let me run the lint proper, hold on.

**Comment by ajkerrigan** [comment]
> PR for issue #7260
> 
> Questions:
> 
>     * How do I update the documentation at https://cloudcustodian.io/docs/aws/resources/kinesis.html#delete? Found the `gh-pages` branch but are there other steps?

First of all, thanks for this contribution! Looks reasonable to me, and the `force` option is consistent with what we use elsewhere :+1: 

As for your question, resource/filter/action documentation is generated from class docstrings. So the `kms-key` docs you see [on the Kinesis page](https://cloudcustodian.io/docs/aws/resources/kinesis.html#aws-kinesis-filters-kms-key) come from [this docstring](https://github.com/cloud-custodian/cloud-custodian/blob/edb3ce11db594dc7410b3a8945cc688d653b76a6/c7n/filters/kms.py#L8-L40). If you add a similar docstring to [the Delete class](https://github.com/cloud-custodian/cloud-custodian/blob/acf4c86583c8e63df9ab4827dd419b5369098365/c7n/resources/kinesis.py#L71), it'll feed into generated docs.

### Side Notes

We've recently changed the way we build docs following PR merges, and are actively troubleshooting an issue with those docs flowing to cloudcustodian.io. You can use `make sphinx` locally to build and preview documentation changes.

**Comment by ajkerrigan** [comment]
Not sure what's up with the CLA check going from green to red without an apparent committer change :thinking:

**Comment by jarylc** [comment]
Yeah that's pretty odd, I'll just sign again. Should we update the docstring for the docs in a separate PR? Or do you think the schema alone is self-explanatory.

**Comment by ajkerrigan** [comment]
Appreciate you checking, I do think it's worth adding examples for cases like this. Seems worth pointing out that force will remove existing consumers, so the intent is clear even to folks who don't dig into the code. For the example policy you may be able to YAMLify the one from your test :).

**Comment by jarylc** [comment]
Alright this should be ready.

**Review by ajkerrigan — APPROVED** [review]
Looks good to me, thanks again!

**Pull request merged**
