### PR TITLE
aws - Adding Transfer Family base resources

### PR DESCRIPTION
**Pull request by TanguyCme**

### CODE REVIEW

**Comment by TanguyCme** [comment]
linked to issue #6927

**Comment by TanguyCme** [comment]
I've added tests for Server resources but I'm struggling a bit with the child resource workflow, for transfer users boto3 need a server id for list_users function, how do we get it ? by overriding get_resources ?

**Review by kapilt — APPROVED** [review]
thanks, lgtm, one minor we should probably limit max workers to 3 vs 10 due to rate limits.

**Comment by TanguyCme** [comment]
Max workers limited to 3, thx :)

**Comment by fivetran-kirillkobylyanskiy** [comment]
Hey! Any updates on this?

**Pull request merged**
