### PR TITLE
aws - rdscluster network-location fix via subnet filter support

### PR DESCRIPTION
**Pull request by kapilt**
addresses #5897

### CODE REVIEW

**Comment by kapilt** [comment]
need to rebase to trunk with just the rds subnet changes

**Comment by PratMis** [comment]
ah, get your changes now! Tested it in the environment where the issue was seen, works well. Thanks

**Comment by PratMis** [comment]
@kapilt do you mind rebasing this one so that we can move forward! Thanks!

**Comment by PratMis** [comment]
@kapilt do you mind fixing your branch here?

**Comment by soncaocc** [comment]
+1 to upvote this. I'm running into the exact same issue as https://github.com/cloud-custodian/cloud-custodian/issues/5897

**Comment by PratMis** [comment]
Nice, this look pretty clean and solves it for all the resources using the `subnet` filter. lgtm

**Pull request merged**
