### PR TITLE
aws - sqs - deadletter filter

### LINKED ISSUE #7463: Add a way to filter out dead-letter-queues from list of SQS queues
### Describe the feature

We are looking [for](url) a way to cleanup our unused AWS SQS queues. We have a policy that filters down to queues that have not been used in the past year. Now we need to be able to filter out dead-letter-queues (DLQs) from the list. We do not want to inadvertently remove any DLQs that are still needed but not receiving messages (because everything works so well).

We had a quick discussion about this in Gitter on May 26-27 and @ajkerrigan gave us a way to identify the DLQs using jq. Hopefully something can be added to custodian to allow us to filter out the DLQs directly from the policy?

### Extra information or context

Here is a bit of what @ajkerrigan had to say in Gitter:

>  this sounds like a feature request for a filter that checks for dead letter source queues. It could use list-dead-letter-source-queues under the hood (alternatively since we already have redrive policies cached for all queues in the region, may be able to leverage that data and save on API calls). It's worth filing as an issue to sort it out though. Ananth's workaround looking for the queue twice in resources.json is interesting though in the meantime.

### PR DESCRIPTION
**Pull request by thisisshi**
Closes #7463

### CODE REVIEW

**Review by kapilt — CHANGES_REQUESTED** [review]
consider the following policy

```yaml
name: sqs-not-used
resource: aws.sqs
filters:
  - tag:Env: Dev
  - deadletter
```

ie. the implementation logic here is assuming positional ordering of filters, which isn't safe.

additionally could use a doc example.

**Comment by thisisshi** [comment]
Ugh... placebo and MacOS not playing nicely, reading the debug logs it seems that sometimes placebo does not actually read all of the flight recordings:

```
DEBUG    placebo.pill:pill.py:141 attaching to session: Session(region_name='us-east-1')
DEBUG    placebo.pill:pill.py:142 datapath: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter
DEBUG    placebo.pill:pill.py:134 _create_client
DEBUG    placebo.pill:pill.py:300 _make_request: sqs.ListQueues
DEBUG    placebo.pill:pill.py:283 load_response: sqs.ListQueues
DEBUG    placebo.pill:pill.py:243 get_next_file_path: sqs.ListQueues
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.ListQueues_1.json
DEBUG    placebo.pill:pill.py:134 _create_client
DEBUG    placebo.pill:pill.py:300 _make_request: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:283 load_response: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:243 get_next_file_path: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:300 _make_request: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:283 load_response: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:243 get_next_file_path: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.GetQueueAttributes_1.json
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.GetQueueAttributes_1.json
DEBUG    placebo.pill:pill.py:300 _make_request: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:283 load_response: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:243 get_next_file_path: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.GetQueueAttributes_3.json
DEBUG    placebo.pill:pill.py:300 _make_request: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:283 load_response: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:243 get_next_file_path: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.GetQueueAttributes_4.json
```

note how `sqs.GetQueueAttributes_1.json` is loaded twice here.

**Comment by thisisshi** [comment]
later on in the tail end of the log when we pull the resources again, we see that the 4th response isn't loaded:

```
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.GetQueueAttributes_1.json
DEBUG    placebo.pill:pill.py:243 get_next_file_path: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.GetQueueAttributes_2.json
DEBUG    placebo.pill:pill.py:300 _make_request: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:283 load_response: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:243 get_next_file_path: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:300 _make_request: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:283 load_response: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:243 get_next_file_path: sqs.GetQueueAttributes
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.GetQueueAttributes_3.json
DEBUG    placebo.pill:pill.py:286 load_response: /Users/sonny/dev/thisisshi/cloud-custodian/tests/data/placebo/test_sqs_deadletter_filter/sqs.GetQueueAttributes_3.json
```

**Review by kapilt — APPROVED** [review]
lgtm, though one minor, i think re naming we should hyphenate as its pretty common throughout our extant filters/actions instead of compounding the words directly. ie. rename to dead-letter

**Comment by kapilt** [comment]
the read twice might be a concurrency issue

**Pull request merged**
