### PR TITLE
aws - rds - bug fix in consecutive-snapshots filter

### PR DESCRIPTION
**Pull request by jasgrover**
This will resolve the bug in the 'consecutive-snapshot' filter  in usage of datetime module.

### CODE REVIEW

**Comment by kapilt** [comment]
given the test failure indicates the changed code was already correct, you'll need to provide additional context on what issue you were seeing (traceback ideally).

**Review by kapilt — COMMENTED** [review]
its not clear this is functionally changing anything, ie the code is equivalent to what it was doing prior to the change.

**Comment by jasgrover** [comment]
not sure why .. but i am getting this error when the code gets deployed at my end. May be its something with my runtime config.
```
[ERROR] AttributeError: module 'datetime' has no attribute 'utcnow'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1295, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 907, in run
    for r in PullMode.run(self):
  File "/var/task/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/resources/rds.py", line 135, in resources
    return super(RDS, self).resources(query=query)
  File "/var/task/c7n/query.py", line 540, in resources
    resources = self.filter_resources(resources)
  File "/var/task/c7n/manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "/var/task/c7n/filters/core.py", line 387, in process
    return self.process_set(resources, event)
  File "/var/task/c7n/filters/core.py", line 411, in process_set
    resources = f.process(resources, event)
  File "/var/task/c7n/resources/rds.py", line 1934, in process
    utcnow = datetime.utcnow()
```

**Comment by kapilt** [comment]
ic, it looks like your targeting fix to the wrong line number.. albeit the module import change should address it, the traceback references `rds.py, line 1934, in process `

**Comment by jasgrover** [comment]
I did  exactly that in my first commit , but the test failed because of mock test method(mock_datetime_now) I used from testing relies on the reference. 

but on the different track , I uncovered strange deployment issue . I see the above error for lambda deployed in one region while other regions in same account have "no issue". So may be we won't need this change

**Comment by jasgrover** [comment]
@kapilt the deployment issue was un related .. We will need this change !!

**Comment by kapilt** [comment]
understood, its a real issue, and this does fix it, but it does so by changing the lines that weren't broken instead of fixing the problematic line directly, which makes it quite hard to infer what the pr fixed without context.

**Comment by jasgrover** [comment]
@kapilt  I agree, the actual line( one with the issue in trace ) was fixed .. please see the latest commit

**Review by kapilt — APPROVED** [review]
thanks, lgtm

**Pull request merged**
