### PR TITLE
Cache assumed credentials across policies

### PR DESCRIPTION
**Pull request by Sutto**
Credentials weren't always cached across session / details - STS assumption can be expensive and quite slow, so we want to avoid doing it too often (in general).

This changes the implementation to cache them (in memory only), and expire them automatically - and share across all the policies in a given run.

In our case with lots of different types / policies (it was written a while ago), it was a pretty substantial performance improvement.

### CODE REVIEW

**Comment by kapilt** [comment]
so i'm missing how this does a refresh aspect, this looks like a permanent process cache.

while we do thread local caching on sts, part of the issue with our sts call volume is we have a bad pattern of separate session construction in thread pool workers thats been copied for other filters/actions. I've tried moving that to a newer pattern but i'll need to revisit extant usage to get total call reduction.

**Comment by kapilt** [comment]
ah ic, regarding the refresh aspect, thats clear now. I'd still like to clean up some of the gratuitous sts assume patterns, before doing a baking off on call count reduction, but its clear this would provide a best case solution on call volume reduction. The assume pattern extant is in part based on a misunderstanding, ie. we construct session per thread and client, in worker pools, on the basis that a client was not thread safe. in fact boto3 clients are thread safe, however their construction is not. i've been retro fitting extant usage modes to construct main thread sessions (should pick up the thread local) for client construction which then passes client to thread pool. Per #2216, Its also proving useful as an excuse for a wider code review.

**Comment by kapilt** [comment]
I started going through all the assume patterns and usages, and I'm coming around to this solution as the best short and medium path fix for this, ideally we have this cache cleared from the same utility function that clears out the thread local session in utils.

**Comment by kapilt** [comment]
i think i've audited and fixed every place i could find any thread pool usage doing a local_session inside and replaced with passing in a client, but its hard to say apropri if its accurate. latest releases do have api call stats tracking in metadata.json, so any policy that has more than one role assume call (and most won't even have that), should. we're also explicitly reusing the session across policies, with the exception of lambdas that do member-role.

**Comment by kapilt** [comment]
#3498 hits the largest pile of session creation in a thread pool, also gave me a chance to audit on a bit more, and remove a few others. we're probably not still at 100% session creation in main thread, but we're significantly closer now.

**Comment by Sutto** [comment]
Closing since it's no longer relevant / needed

**Comment by kapilt** [comment]
I’m not sure we are fully past it yet, I ran into some spots for the asg resource that I saw a few thread pool session creations recently

**Pull request closed without merging**
