### PR TITLE
Fix issue for creation time when LogGroup is empty

### PR DESCRIPTION
**Pull request by zagaria**
If no streams - LastWriteDays try to get creation time from the group. But this value in seconds instead of milliseconds.

Just added multiplication on 1000 for CW LogGroup for minimal code changes.

### CODE REVIEW

**Comment by kapilt** [comment]
Nice catch. Thanks for the pull request!  If you don't mind could you sign the CLA per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by zagaria** [comment]
Done. @kapilt please check Google form

**Comment by zagaria** [comment]
Hi @kapilt !

Can you, please, provide information when this fix will be merged (version)? Or need additional actions for it?

Thanks!

**Comment by kapilt** [comment]
we need a unit test to get ci passing, as its currently failing on coverage for the change.

**Comment by zagaria** [comment]
@kapilt but I don't see how my change affect the coverage https://codecov.io/gh/cloud-custodian/cloud-custodian/compare/dc087d1902e82d74d120a65af2ee22ec27f0d9b2...e7631e15337258b44ab8f6d8048bc284b0adf73c/changes#

Should refork repository and prepare changes again?

**Comment by kapilt** [comment]
its because the line wasn't previously covered

**Comment by zagaria** [comment]
Is it must be something like this? https://github.com/cloud-custodian/cloud-custodian/blob/master/tests/test_cwl.py#L34

If yes, how I can prepare changes for the AWS resource template? Or it's integration tests?

**Comment by zagaria** [comment]
Hi @kapilt! 

Is it not possible to merge this request? How can I help with it?

Thanks.

**Comment by kapilt** [comment]
its a flight record against a real environment that forms the basis of the test, some of this is in our developer docs, wrt to the test code, its switching replay_flight_data to record_flight_data, the test machinery will automatically sanitize account ids in recorded output.

**Comment by zagaria** [comment]
Hi @kapilt 

Can you, please, help with it? Because I don't understand how this change affect coverage in S3 coverage. 

In tests I found test for creation time https://github.com/cloud-custodian/cloud-custodian/blob/master/tests/test_cwl.py

Also, from time to time CI failed on master source without any changes.
image

Thanks!

**Comment by tjstansell** [comment]
This doesn't seem correct, at least anymore... according to the API docs, this time is in milliseconds:
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_LogGroup.html

**Comment by tjstansell** [comment]
Testing against my c7n log group agrees:
```
$ aws logs describe-log-groups --log-group-name-prefix cloud-custodian
{
    "logGroups": [
        {
            "logGroupName": "cloud-custodian",
            "creationTime": 1551238705282,
            "retentionInDays": 14,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:us-west-2:123456789012:log-group:cloud-custodian:*",
            "storedBytes": 38409318
        }
    ]
}
```
`1551238705282` is a millisecond epoch.

**Comment by kapilt** [comment]
another pr in #6069 was merged that handled this same case and added some tests.

**Pull request closed without merging**
