### PR TITLE
aws - workspaces kms key filter

### PR DESCRIPTION
**Pull request by Lucas-Irvine**
Add a workspaces kms key filter

### CODE REVIEW

**Comment by Share-Holdings** [comment]
@kapilt I was wondering if it's possible for you to override the CLA check for now? Our organization is working on getting the new CLA setup @johnmark but not sure how long that'll take.

**Comment by Lucas-Irvine** [comment]
Hi @kapilt I was wondering if it's possible to override the CLA check for now? Our organization is working on getting the new CLA setup @johnmark but not sure how long that'll take.

**Comment by kapilt** [comment]
Hi @Lucas-Irvine i'll use the google cla form/spreadsheet as sufficient for in progress prs. i'm talking to @johnmark and linux foundation re issues with easycla.

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Pull request merged**
