### PR TITLE
aws - dynamodb - enhancement recommended for the consecuitive-backups filter

### PR DESCRIPTION
**Pull request by jasgrover**
Comments in https://github.com/cloud-custodian/cloud-custodian/pull/7750  and https://github.com/cloud-custodian/cloud-custodian/pull/7749#issuecomment-1246049342 raised an issue of moving the hard coded attributes as parameters to the resource filter so that it allows for richer attribute filtering.

### CODE REVIEW

**Comment by jasgrover** [comment]
@thisisshi could you please review the changes and confirm if this is what you were expecting through your comments in PR-7749 .. cc @darrendao

**Comment by jasgrover** [comment]
@thisisshi  could you please review  and let me know your thoughts

**Review by thisisshi — COMMENTED** [review]
thanks, lgtm can you add some tests around the new schema options (period, status, back up type)

**Comment by jasgrover** [comment]
@thisisshi updated the tests

**Comment by jasgrover** [comment]
@thisisshi @ajkerrigan @StevenGunn @darrendao hi there .. could someone please review this one .

**Comment by thisisshi** [comment]
@jasgrover you didnt really update the tests... you're still only testing for days, there's no checks on if the weeks or hours logic work

**Comment by jasgrover** [comment]
@thisisshi Sorry missed the warnings in coverage report .. added tests for other filter attributes , ie hours and weeks

**Review by thisisshi — APPROVED** [review]

**Pull request merged**
