### PR TITLE
keypair enhanced with asg check too

### PR DESCRIPTION
**Pull request by linuxananth1976**
update key-pair with asg validation in vpc resource.

### CODE REVIEW

**Comment by linuxananth1976** [comment]
@ajkerrigan @kapilt facing this issue in CI
`ruff c7n tests tools
Error: tools/ops/logsetup.py:70:9: F823 Local variable `sys` referenced before assignment
make: *** [Makefile:65: lint] Error 1
Error: Process completed with exit code 2.`
Is there anything missed from my side?

**Comment by linuxananth1976** [comment]
Screenshot 2023-07-24 at 12 21 44

**Comment by ajkerrigan** [comment]
> Screenshot 2023-07-24 at 12 21 44
> 
> @ajkerrigan @kapilt FYR

Thanks for pointing this out @linuxananth1976 . That code hasn't changed in years but it looks like it's confusing ruff because it imports `sys` twice so the reference in between the two imports looks unexpected.

My suspicion is that's a bug, but I opened https://github.com/astral-sh/ruff/issues/6029 to sort that out. Importing `sys` twice feels unnecessary in any case, so also opened #8758 to avoid the issue from our end.

**Comment by kapilt** [comment]
@linuxananth1976 fix the lint issue was merged to trunk and this pr.

**Comment by linuxananth1976** [comment]
@ajkerrigan @kapilt I hope I'm done.  If there anything missed out let me know.  Thanks please have a review on it.

**Review by ajkerrigan — APPROVED** [review]
Thanks for the addition and cleanup, looks good :+1:

**Review by kapilt — APPROVED** [review]
lgtm

**Pull request merged**
