### PR TITLE
Pre commit hook

### LINKED ISSUE #9555: validate pre-commit hook?
### Describe the feature

It would be nice to get fast feedback for testing policy validations when committing changes with a pre-commit hook. Not sure if this has been requested before, apologies if so.

### Extra information or context

Currently I am testing validations manually and sometimes forget.

### PR DESCRIPTION
**Pull request by jmreicha**
Adds the ability to run a pre-commit hook on changed policies.

I figured I would start with the normal pre-commit usage and add in the Docker functionality in a separate PR when I get more free time to play with it.

Here's an example usage with a `test.yaml` file for testing the hook.

```yaml
policies:
  - name: test-pre-commit
    description: Testing pre-commit hook
    resource: foo
    mode:
      role: arn:aws:iam::{account_id}:role/myrole
      schedule: "rate(1 day)"
      type: periodic
      tags:
        test: test
```

And an example pre-commit config.

```yaml
repos:
  - repo: https://github.com/jmreicha/cloud-custodian.git
    rev: f491f0a051fbaf85332e44d8140fc6967e469e2e
    hooks:
      - id: c7n-validate
        files: policies/.*\.yml$
        args:
          # - --strict
          # - --verbose
          - --quiet
```

And here's the output.

```bash
pre-commit run --files policies/test.yml 
cloud custodian validate.................................................Failed
- hook id: c7n-validate
- exit code: 1

2024-06-22 11:47:51,854: custodian.commands:ERROR Configuration invalid: policies/test.yml
2024-06-22 11:47:51,855: custodian.commands:ERROR             Error on policy:test-pre-commit resource:foo
{'name': 'test-pre-commit', 'description': 'Testing pre-commit hook', 'resource': 'foo', 'mode': {'role': 'arn:aws:iam::{account_id}:role/myrole', 'schedule': 'rate(1 day)', 'type': 'periodic', 'tags': {'test': 'test'}}} is not valid under any of the given schemas

            Failed validating 'anyOf' in schema['properties']['policies']['items']:
                {'anyOf': [{'$ref': '#/definitions/resources/aws.ec2/policy'},
                           {'$ref': '#/definitions/resources/aws.ec2-capacity-reservation/policy'},
                           {'$ref': '#/definitions/resources/aws.ec2-host/policy'},
                           {'$ref': '#/definitions/resources/aws.ec2-reserved/policy'},
                           {'$ref': '#/definitions/resources/aws.ec2-spot-fleet-request/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-certificate/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-group/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-oidc-provider/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-policy/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-profile/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-role/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-saml-provider/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-user/policy'},
                           {'$ref': '#/definitions/resources/aws.launch-template-version/policy'},
                           {'$ref': '#/definitions/resources/aws.ops-item/policy'},
                           {'$ref': '#/definitions/resources/aws.securityhub-finding/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-activation/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-data-sync/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-document/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-managed-instance/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-parameter/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-patch-group/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-session-manager/policy'},
                           {'$ref': '#/definitions/resources/aws.step-machine/policy'}]}

            On instance['policies'][0]:
                {'description': 'Testing pre-commit hook',
                 'mode': {'role': 'arn:aws:iam::{account_id}:role/myrole',
                          'schedule': 'rate(1 day)',
                          'tags': {'test': 'test'},
                          'type': 'periodic'},
                 'name': 'test-pre-commit',
                 'resource': 'foo'}
2024-06-22 11:47:51,855: custodian.commands:ERROR test-pre-commit
```

Let me know if this looks right.

Closes #9555.

### CODE REVIEW

**Comment by kapilt** [comment]
thanks, but shouldn't this be in the docs re how to setup?

**Comment by jmreicha** [comment]
Yep I will get that added.

**Comment by ajkerrigan** [comment]
> Yep I will get that added.

Thanks! Aside from that the change looks good to me too, should be helpful to have. Regarding doc placement, my first thought is that it makes sense as a heading/section under [Getting Started](https://cloudcustodian.io/docs/quickstart/index.html). Possibly somewhere around the Editor Integration section?

There may be a more obvious spot that's eluding me though.

**Comment by jmreicha** [comment]
Ok I got some basic docs added, let me know if that works. Otherwise, I can add anything that's missing.

**Comment by kapilt** [comment]
if we have the instructions in the doc, is there any reason to have the top level file in the repo, given its not actually in use. otherwise lgtm

**Comment by ajkerrigan** [comment]
I'm good with this now, thanks!

FWIW we do need the top level file, because if policy authors reference the `https://github.com/cloud-custodian/cloud-custodian.git` repo in a `.pre-commit-config.yaml` file, it'll look for hooks in our top-level `.pre-commit-hooks.yaml`.

**Review by ajkerrigan — APPROVED** [review]
Looks good, thanks for taking this on and documenting it :+1:

**Comment by kapilt** [comment]
That seems like a supply chain risk tbh if that's a default for pre commit, 🤷🏽‍♂️.

**Comment by jmreicha** [comment]
Most of the hooks I have seen are bundled in the hosting repo. Otherwise, the hook could either be hosted in a new repo or used as a [local hook](https://pre-commit.com/#developing-hooks-interactively). I can't really speak to the attack vector but I know some large projects use it.

Here are a few examples:

Bundled

- https://github.com/pre-commit/pre-commit-hooks/blob/main/.pre-commit-hooks.yaml
- https://github.com/google/yapf/blob/main/.pre-commit-hooks.yaml
- https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml

Separate repo

- https://github.com/astral-sh/ruff-pre-commit/blob/main/.pre-commit-hooks.yaml

**Pull request merged**
