### PR TITLE
aws - security-group - used filter - add interface usage annotation

### PR DESCRIPTION
**Pull request by naohito-intuit**
Following up on #7919, further enhancement to the `used` filter to annotate interface usage information extracted from the `Description` attribute in the ENI resource. The resource mapping is based on the [zerodark example](https://github.com/cloud-custodian/cloud-custodian/blob/e9410542cda9714d76d32e8e6770349cb5119e3e/tools/sandbox/zerodark/zerodark/ipdb.py#L101-L174). The resource usage is determined only by the `Description` attribute except for `ec2`. It intentionally ignores to reference other attributes such as `InstanceOwnerId` or `InterfaceType`.

**Changes from the zerodark example**
- Rename resources
  - `alb` -> `elb-app`
  - `nlb` -> `elb-net`
  - `efs-mount` -> `fsmt`
- Add `apigw`, `codestar`, `elb-gwy`, `tgw`
- Update matching patterns

**Example**
```yaml
policies:
  - name: security-group-used-by-alb
    resource: security-group
    filters:
      - type: used
      - type: value
        key: c7n:InterfaceResourceTypes
        op: intersect
        value:
          - elb-app
```

### CODE REVIEW

**Comment by kapilt** [comment]
this method should probably a utility function that accepts the nic resource, so it can be used across other callers.

**Comment by kapilt** [comment]
looks good, but can we have a validation test on the output inclusive of the new annotation?

**Comment by naohito-intuit** [comment]
@kapilt I have added a validation test on the used filter for the new annotations. Please review.

**Review by thisisshi — APPROVED** [review]
thanks, lgtm

**Pull request merged**
