### PR TITLE
Azure - doc fix formatting

### PR DESCRIPTION
**Pull request by stefangordon**

### CODE REVIEW

**Comment by stefangordon** [comment]
@kapilt Something is broken with CI - seems like builds are not being queued for PR's much of the time?  Saw it happen to your PR and a few of mine yesterday and today.   Has this been going on a while or did it start yesterday?

**Comment by kapilt** [comment]
@stefangordon it started yesterday, seems like something is up for azure devops, but status board only shows something unrelated else green.

**Comment by kapilt** [comment]
actually it feels like it started early this morning

**Comment by stefangordon** [comment]
Yeah I have had 3 or 4 times already this morning, closing and reopening the PR is the easiest fix I have found so far and is enough to trigger it.

**Comment by stefangordon** [comment]
Update: I have a support incident going on this

**Pull request merged**
