### PR TITLE
Add event body to webhook action

### PR DESCRIPTION
**Pull request by vauchok**

### CODE REVIEW

**Comment by vauchok** [comment]
#6279

**Comment by kapilt** [comment]
Thanks for the pull request!  looks good to me, If you don't mind could you sign the CLA per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by vauchok** [comment]
> Thanks for the pull request! looks good to me, If you don't mind could you sign the CLA per the developer docs? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

Done and thank you.

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Pull request merged**
