### PR TITLE
efs-mount-point network-location filter

### PR DESCRIPTION
**Pull request by mattheidelbaugh**
Resolves https://github.com/cloud-custodian/cloud-custodian/issues/8231

### CODE REVIEW

**Comment by kapilt** [comment]
see discussion on https://github.com/cloud-custodian/cloud-custodian/pull/7909

**Comment by mattheidelbaugh** [comment]
> see discussion on #7909

This is for efs mount target

**Comment by kapilt** [comment]
@mattheidelbaugh 👍

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Pull request merged**
