### PR TITLE
aws - iam-user - add set-policy action (#8115)

### PR DESCRIPTION
**Pull request by pmoody-**

### CODE REVIEW

**Comment by thisisshi** [comment]
Hi, thanks for the contribution, looks like this is your first contribution. Could you please take a look at and sign the CLA linked above? Direct link here: https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/14202841/52837350/7664/#/?version=2 Thank you!

**Comment by pmoody-** [comment]
> Could you please take a look at and sign the CLA linked above? Direct link here: https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/14202841/52837350/7664/#/?version=2 Thank you!

alright, this _should_ be signed. there were some issues with my username/email but 🤞 everything is good now.

**Comment by thisisshi** [comment]
could you add a test for this?

**Comment by pmoody-** [comment]
just following up, is there anything else you wanted from me on this?

**Review by kapilt — APPROVED** [review]
thanks, lgtm

**Pull request merged**
