### PR TITLE
cli - Generate iam role

### PR DESCRIPTION
**Pull request by anovis**
#888 Allow users to generate iam roles from the cli based on their policies. 
``` custodian generate-role custodian.yaml ```

can be run with ```--dryrun``` to just output the policy doc

can also specify ```--role``` and ```--policy``` to set the role and policy name otherwise a random hash will be created for them.

### CODE REVIEW

**Comment by kapilt** [comment]
most of my comments from sonny's pr apply here, this belongs in tools (probably an ops script), its not multi-cloud ready.

**Comment by kapilt** [comment]
re that previous pr #3642

**Comment by kapilt** [comment]
I think that this has enough issues in terms of interface and nuance on permissions that the pr is not getting or making distinction on that we should just close this and discuss at the pycon sprint. As is imo, this is going to cause more questions and problems for users than providing answers or solutions.

**Comment by anovis** [comment]
makes sense. will close then for now. thanks!

**Pull request closed without merging**
