### PR TITLE
Add filter for Workspaces connection status

### PR DESCRIPTION
**Pull request by ajkerrigan-mdsol**
Add a `connection-status` value filter which can pull in `describe_connection_status` information as needed.

Related to #3729

### CODE REVIEW

**Comment by ajkerrigan-mdsol** [comment]
I did some wiggling with `__call__` so that this filter would match on `c7n:ConnectionStatus` but annotate matches at the top-level `c7n:MatchedFilters`. It feels pretty awkward though, so I'm betting I missed a cleaner way to handle that. Maybe with `merge_annotation` directly in `process`?

**Comment by kapilt** [comment]
thanks for the pull request, I'm not sure I understand the question your making on annotations. there are two annotation keys in the pr, the bespoke matched one that value filter does, and then the status annotation. the later looks fine. The former does seem a little strained, the simpler alternative might be to just override get_resource_value  on a value filter to use the annotation and call super.

```python
def get_resource_value(self, k, i):
      return super(k[self.annotation_key], i)
```

which avoids overriding __call__ which will get the default behavior there. 

for this one I'd probably suggest annotate = False on the filter class, Its unclear that the bespoke value filter annotation really applies well here.

**Comment by ajkerrigan-mdsol** [comment]
Oh yes, overriding `get_resource_value` is a much cleaner way to handle that. Thanks for the nudge! 👍 

I didn't add `annotate = False` (yet), because I'm thinking about policies where I'll be filtering on a combination of connection status info and metrics. I think in those cases seeing a match annotation for something like `LastKnownUserConnectionTimestamp` will be useful. That's not a super strong argument, so if you disagree I'm cool with adding `annotate = False` before pushing this through.

**Comment by kapilt** [comment]
sounds good re annotate

**Pull request merged**
