### PR TITLE
Fixes SecurityHub cwe detail-type mismatch #4497 

### PR DESCRIPTION
**Pull request by FireballDWF**
Fixes issue #4497 by using correct event string

### CODE REVIEW

**Comment by kapilt** [comment]
Fwiw, it would be helpful to have clean fit histories for the changes, the commit lineage goes on this back quite a while and is almost entirely unrelated to the pull request change.

**Comment by kapilt** [comment]
Also please use the pr description to reference issues so they are turned into links instead of putting them in titles.

**Comment by kapilt** [comment]
we don't really want mu to depend on policy, its intended as foundational infrastructure that can be used independently of policies.

**Comment by FireballDWF** [comment]
Closing this PR in favor of #4524

**Pull request closed without merging**
