### PR TITLE
releng - update codecov action

### PR DESCRIPTION
**Pull request by kapilt**
codecov seems to be barfing at the moment on uploads, and their status site shows nothing. try updating the codecov 
action to latest and greatest to see if it resolves. for ref the issue we're seeing.

```
[2022-10-20T17:22:43.103Z] ['verbose'] parent
63
[2022-10-20T17:22:43.104Z] ['info'] Pinging Codecov: 
https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.3.2&token=*******&branch=add-rds-proxy-resource&build=3291567706&build_url=https%3A%2F%2Fgithub.com%2Fcloud-custodian%2Fcloud-custodian%2Factions%2Fruns%2F3291567706&commit=c743f6c1e45b25df09bffa0ad04dba281ece80fd&job=CI&pr=7859&service=github-actions&slug=cloud-custodian%2Fcloud-custodian&name=codecov&tag=&flags=&parent=
64
[2022-10-20T17:22:43.104Z] ['verbose'] Passed token was 0 characters long
65
[2022-10-20T17:22:43.104Z] ['verbose'] 
https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.3.2&branch=add-rds-proxy-resource&build=3291567706&build_url=https%3A%2F%2Fgithub.com%2Fcloud-custodian%2Fcloud-custodian%2Factions%2Fruns%2F3291567706&commit=c743f6c1e45b25df09bffa0ad04dba281ece80fd&job=CI&pr=7859&service=github-actions&slug=cloud-custodian%2Fcloud-custodian&name=codecov&tag=&flags=&parent=
66
        Content-Type: 'text/plain'
67
        Content-Encoding: 'gzip'
68
        X-Reduced-Redundancy: 'false'
69
[2022-10-20T17:22:43.262Z] ['error'] There was an error running the uploader: Error uploading to 
https://codecov.io: Error: There was an error fetching the storage URL during POST: 503 - upstream connect error or 
disconnect/reset before headers. reset reason: connection failure
70
[2022-10-20T17:22:43.262Z] ['verbose'] The error stack is: Error: Error uploading to https://codecov.io: Error: 
There was an error fetching the storage URL during POST: 503 - upstream connect error or disconnect/reset before 
headers. reset reason: connection failure
71
    at main (/snapshot/repo/dist/src/index.js)
72
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
73
[2022-10-20T17:22:43.262Z] ['verbose'] End of uploader: 1066 milliseconds
```

### CODE REVIEW

**Review by thisisshi — APPROVED** [review]

**Comment by kapilt** [comment]
This appears to be the underlying issue, and its a service side codecov to GitHub in support of public repos sans codecov tokens hitting rate limit things.

https://github.com/codecov/codecov-action/issues/557
https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652

its unclear that we have a great option on resolution, secrets don't work well by design against pull requests from fork. I'm not really seeing a lot of chat on this on the codecov repos or twitter, investigating alternatives.

**Comment by kapilt** [comment]
in terms of alternatives, we got to codecov as an alternative to coveralls. perhaps we need something simpler then a third party saas.

ie re simple, a tool that takes the client side coverage output and update a GitHub comment on a pr, ideally with GitHub annotations on coverage. the second one seems to have started about the same time codecov went awol. 
https://github.com/py-cov-action/python-coverage-comment-action
https://github.com/orgoro/coverage

**Comment by kapilt** [comment]
Fwiw, they seemed to have resolved the issue.

**Comment by thisisshi** [comment]
@kapilt want to still merge this in? If it works I dont see why not

**Comment by kapilt** [comment]
Yeah let's merge, it switches out from the bash uploader script to a golang binary

**Pull request merged**
