### PR TITLE
azure - filter - use retry

### PR DESCRIPTION
**Pull request by iamanmolm**
This fixes issue reported in https://github.com/cloud-custodian/cloud-custodian/issues/9346

### CODE REVIEW

**Comment by kapilt** [comment]
per comments in #9363 its an open question on how this is interacting with extant provider usage/customization of native sdk retry behavior.

**Comment by iamanmolm** [comment]
> per comments in #9363 its an open question on how this is interacting with extant provider usage/customization of native sdk retry behavior.

@kapilt so to nail the problem down, what I did was tried running multiple custodian commands in parallel over same subscription/tenant. Here what I see was normally without any code changes it works fine for 7-8 times but after that throws the same error. But with the code changes it works fine for 12-13 times. Maybe instead of adding new retry mechanism. I can change max_retries to let say 8 and test it out. Thoughts?

**Comment by iamanmolm** [comment]
@kapilt the fix is now much simpler. Rather than adding new retry mechanism, I have just increased number of retries to 8 similar to what was there in AWS retry mechanism as well.

**Review by kapilt — APPROVED** [review]
Thanks, lgtm

**Pull request merged**
