### PR TITLE
Resolved: AttributeError: 'FunctionAppInfrastructureParameters' object has no attribute 'function_app_name'

### PR DESCRIPTION
**Pull request by bhvkrishna90**
When trying to create policies using Function hosting, Getting below error.

File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/c7n_azure/policy.py", line 446, in provision
    queue_name = re.sub(r'(-{2,})+', '-', self.function_params.function_app_name.lower())
AttributeError: 'FunctionAppInfrastructureParameters' object has no attribute 'function_app_name'

After Going through code, there is an issue with function_app_name attribute in FunctionAppInfrastructureParameters object.

Corrected Attribute values.

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks for the pull request!  If you don't mind could you sign the CLA at the bottom of the README? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by bhvkrishna90** [comment]
> Thanks for the pull request! If you don't mind could you sign the CLA at the bottom of the README? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by bhvkrishna90** [comment]
Signed CLA.

**Review by kapilt — APPROVED** [review]
lgtm, thanks

**Pull request merged**
