### PR TITLE
WIP Adding filter for RequesterManaged ENIs

### PR DESCRIPTION
**Pull request by schledererj**
#3406

### CODE REVIEW

**Comment by kapilt** [comment]
thanks for the pr, so i think we would also want to log a warning iff we're actually filtering anything out implicitly.

**Comment by schledererj** [comment]
I agree. Also, as I mentioned in the related issue, I don't think this will actually do anything, so I'm still working/thinking about something that will. Just wanted to get this out there as a preliminary idea.

**Comment by kapilt** [comment]
as an approach its fine, we do some of this in a few other actions. we typically do something like

```python
rcount = len(interfaces)
interfaces = [i for for i in interfaces if i.get('RequesterManaged')]
if len(interfaces) != rcount:
    self.log.warning("Implicitly filtered requested managed interfaces from %d to %d",
           rcount, len(interfaces))
```

**Comment by schledererj** [comment]
Closing this. The approach I'm using won't work, so I'll submit a new one.

**Pull request closed without merging**
